<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'BSMID',
'PROPNO',
'REGDATE',
'TTG',
'SDATE',
'EDATE',
'MTUSI',
'SI',
'RATE',
'RATEUNIT',
'MTUPREMI',
'PREMI',
'KODETOC',
'STATUS',
'LASTUSER',
'MODEBISNISBSM' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'BSMID' => array( 'import_field' ),
'PROPNO' => array( 'import_field1' ),
'REGDATE' => array( 'import_field2' ),
'TTG' => array( 'import_field3' ),
'SDATE' => array( 'import_field4' ),
'EDATE' => array( 'import_field5' ),
'MTUSI' => array( 'import_field6' ),
'SI' => array( 'import_field7' ),
'RATE' => array( 'import_field8' ),
'RATEUNIT' => array( 'import_field9' ),
'MTUPREMI' => array( 'import_field10' ),
'PREMI' => array( 'import_field11' ),
'KODETOC' => array( 'import_field12' ),
'STATUS' => array( 'import_field13' ),
'LASTUSER' => array( 'import_field14' ),
'MODEBISNISBSM' => array( 'import_field15' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'BSMID',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'PROPNO',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'REGDATE',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'TTG',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'SDATE',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'EDATE',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'MTUSI',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'SI',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'RATE',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'RATEUNIT',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'MTUPREMI',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'PREMI',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'KODETOC',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'STATUS',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'LASTUSER',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'MODEBISNISBSM',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>