<?php
			$optionsArray = array( 'totals' => array( 'IDTEMPCE' => array( 'totalsType' => '' ),
'NOLOANDISBURSE' => array( 'totalsType' => '' ),
'NAMATERJAMIN' => array( 'totalsType' => '' ),
'POKOKPEMBIAYAAN' => array( 'totalsType' => '' ),
'JANGKAWAKTU' => array( 'totalsType' => '' ),
'TGLAKAD' => array( 'totalsType' => '' ),
'TGLJATUHTEMPO' => array( 'totalsType' => '' ),
'KDCBGBANK' => array( 'totalsType' => '' ),
'NMCBGBANK' => array( 'totalsType' => '' ),
'ADDUSER' => array( 'totalsType' => '' ),
'ADDDATE' => array( 'totalsType' => '' ),
'NIK' => array( 'totalsType' => '' ),
'TGLLAHIR' => array( 'totalsType' => '' ),
'ALAMAT' => array( 'totalsType' => '' ),
'BSMID' => array( 'totalsType' => '' ),
'PROPOSALNO' => array( 'totalsType' => '' ),
'PREMI' => array( 'totalsType' => '' ),
'RATE' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'NOLOANDISBURSE',
'NAMATERJAMIN',
'POKOKPEMBIAYAAN',
'JANGKAWAKTU',
'TGLAKAD',
'TGLJATUHTEMPO',
'KDCBGBANK',
'NMCBGBANK',
'ADDDATE',
'NIK',
'TGLLAHIR',
'ALAMAT',
'BSMID',
'PROPOSALNO',
'PREMI',
'RATE' ),
'exportFields' => array( 'NOLOANDISBURSE',
'NAMATERJAMIN',
'POKOKPEMBIAYAAN',
'JANGKAWAKTU',
'TGLAKAD',
'TGLJATUHTEMPO',
'KDCBGBANK',
'NMCBGBANK',
'ADDDATE',
'NIK',
'TGLLAHIR',
'ALAMAT',
'BSMID',
'PROPOSALNO',
'PREMI',
'RATE' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'NOLOANDISBURSE' => array( 'export_field1' ),
'NAMATERJAMIN' => array( 'export_field2' ),
'POKOKPEMBIAYAAN' => array( 'export_field3' ),
'JANGKAWAKTU' => array( 'export_field4' ),
'TGLAKAD' => array( 'export_field5' ),
'TGLJATUHTEMPO' => array( 'export_field6' ),
'KDCBGBANK' => array( 'export_field7' ),
'NMCBGBANK' => array( 'export_field8' ),
'ADDDATE' => array( 'export_field10' ),
'NIK' => array( 'export_field' ),
'TGLLAHIR' => array( 'export_field9' ),
'ALAMAT' => array( 'export_field11' ),
'BSMID' => array( 'export_field12' ),
'PROPOSALNO' => array( 'export_field13' ),
'PREMI' => array( 'export_field14' ),
'RATE' => array( 'export_field15' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field10',
'export_field',
'export_field9',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field10' => 'grid',
'export_field' => 'grid',
'export_field9' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field10',
'export_field',
'export_field9',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field10',
'export_field',
'export_field9',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field1' => array( 'field' => 'NOLOANDISBURSE',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'NAMATERJAMIN',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'POKOKPEMBIAYAAN',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'JANGKAWAKTU',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'TGLAKAD',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'TGLJATUHTEMPO',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'KDCBGBANK',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'NMCBGBANK',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'ADDDATE',
'type' => 'export_field' ),
'export_field' => array( 'field' => 'NIK',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'TGLLAHIR',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'ALAMAT',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'BSMID',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'PROPOSALNO',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'PREMI',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'RATE',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>