<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'NOLOANDISBURSE',
'NAMATERJAMIN',
'POKOKPEMBIAYAAN',
'JANGKAWAKTU',
'TGLAKAD',
'TGLJATUHTEMPO',
'KDCBGBANK',
'NMCBGBANK',
'ADDDATE',
'NIK',
'TGLLAHIR',
'ALAMAT',
'BSMID',
'PROPOSALNO',
'PREMI',
'RATE' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'NOLOANDISBURSE' => array( 'import_field1' ),
'NAMATERJAMIN' => array( 'import_field2' ),
'POKOKPEMBIAYAAN' => array( 'import_field3' ),
'JANGKAWAKTU' => array( 'import_field4' ),
'TGLAKAD' => array( 'import_field5' ),
'TGLJATUHTEMPO' => array( 'import_field6' ),
'KDCBGBANK' => array( 'import_field7' ),
'NMCBGBANK' => array( 'import_field8' ),
'ADDDATE' => array( 'import_field10' ),
'NIK' => array( 'import_field' ),
'TGLLAHIR' => array( 'import_field9' ),
'ALAMAT' => array( 'import_field11' ),
'BSMID' => array( 'import_field12' ),
'PROPOSALNO' => array( 'import_field13' ),
'PREMI' => array( 'import_field14' ),
'RATE' => array( 'import_field15' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field10',
'import_field',
'import_field9',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field10' => 'grid',
'import_field' => 'grid',
'import_field9' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field10',
'import_field',
'import_field9',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field10',
'import_field',
'import_field9',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field1' => array( 'field' => 'NOLOANDISBURSE',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'NAMATERJAMIN',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'POKOKPEMBIAYAAN',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'JANGKAWAKTU',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'TGLAKAD',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'TGLJATUHTEMPO',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'KDCBGBANK',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'NMCBGBANK',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'ADDDATE',
'type' => 'import_field' ),
'import_field' => array( 'field' => 'NIK',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'TGLLAHIR',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'ALAMAT',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'BSMID',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'PROPOSALNO',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'PREMI',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'RATE',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>