<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'NOPROPOSAL',
'KODEKC',
'AWAL' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'NOPROPOSAL' => array( 'integrated_search_field',
'search_field_label1',
'search_field_options1',
'search_field_between1' ),
'KODEKC' => array( 'integrated_search_field1',
'search_field_label2',
'search_field_options2',
'search_field_between2' ),
'AWAL' => array( 'integrated_search_field5',
'search_field_label',
'search_field_options',
'search_field_between' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ),
'top' => array( 'search_header' ),
'grid' => array( 'search_field_label2',
'search_field_label1',
'integrated_search_field',
'search_field_between1',
'integrated_search_field1',
'search_field_between2',
'integrated_search_field5',
'search_field_between',
'search_field_options1',
'search_field_options2',
'search_field_options',
'search_field_label' ) ),
'formXtTags' => array( 'above-grid' => array(  ) ),
'itemForms' => array( 'search_search' => 'below-grid',
'search_reset' => 'below-grid',
'search_back_list' => 'below-grid',
'search_cancel' => 'below-grid',
'search_header' => 'top',
'search_field_label2' => 'grid',
'search_field_label1' => 'grid',
'integrated_search_field' => 'grid',
'search_field_between1' => 'grid',
'integrated_search_field1' => 'grid',
'search_field_between2' => 'grid',
'integrated_search_field5' => 'grid',
'search_field_between' => 'grid',
'search_field_options1' => 'grid',
'search_field_options2' => 'grid',
'search_field_options' => 'grid',
'search_field_label' => 'grid' ),
'itemLocations' => array( 'search_field_label2' => array( 'location' => 'grid',
'cellId' => 'c' ),
'search_field_label1' => array( 'location' => 'grid',
'cellId' => 'c5' ),
'integrated_search_field' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'search_field_between1' => array( 'location' => 'grid',
'cellId' => 'c6' ),
'integrated_search_field1' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'search_field_between2' => array( 'location' => 'grid',
'cellId' => 'c7' ),
'integrated_search_field5' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'search_field_between' => array( 'location' => 'grid',
'cellId' => 'c8' ),
'search_field_options1' => array( 'location' => 'grid',
'cellId' => 'c9' ),
'search_field_options2' => array( 'location' => 'grid',
'cellId' => 'c10' ),
'search_field_options' => array( 'location' => 'grid',
'cellId' => 'c11' ),
'search_field_label' => array( 'location' => 'grid',
'cellId' => 'c1' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'search_header' => array( 'search_header' ),
'search_reset' => array( 'search_reset' ),
'search_back_list' => array( 'search_back_list' ),
'search_search' => array( 'search_search' ),
'search_cancel' => array( 'search_cancel' ),
'search_field' => array( 'integrated_search_field',
'integrated_search_field1',
'integrated_search_field5' ),
'search_field_label' => array( 'search_field_label',
'search_field_label1',
'search_field_label2' ),
'search_field_options' => array( 'search_field_options',
'search_field_options1',
'search_field_options2' ),
'search_field_between' => array( 'search_field_between',
'search_field_between1',
'search_field_between2' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c5' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array( 'NOPROPOSAL_fieldblock' ),
'items' => array( 'search_field_label1' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'search_field_options1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field',
'search_field_between1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array( 'KODEKC_fieldblock' ),
'items' => array( 'search_field_label2' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'search_field_options2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field1',
'search_field_between2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c1' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array( 'AWAL_fieldblock' ),
'items' => array( 'search_field_label' ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c11' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'search_field_options' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 2 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_search_field5',
'search_field_between' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 3 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'search',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'search',
'type' => 'search',
'layoutId' => 'nomenu',
'disabled' => 0,
'default' => 1,
'forms' => array( 'above-grid' => array( 'modelId' => 'search-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ),
'orientation' => 'vertical' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'search-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_search',
'search_reset',
'search_back_list',
'search_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'search-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'search_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-search',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c5',
'colspan' => 1 ),
array( 'cell' => 'c9' ),
array( 'cell' => 'c6' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c10' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c11' ),
array( 'cell' => 'c8' ) ) ) ),
'cells' => array( 'c' => array( 'model' => 'c5',
'items' => array( 'search_field_label2' ),
'useFullWidth' => true,
'orientation' => 'horizontal' ),
'c5' => array( 'model' => 'c5',
'items' => array( 'search_field_label1' ),
'useFullWidth' => true,
'orientation' => 'horizontal' ),
'c6' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field',
'search_field_between1' ),
'orientation' => 'horizontal' ),
'c7' => array( 'model' => 'c3',
'items' => array( 'integrated_search_field1',
'search_field_between2' ),
'orientation' => 'horizontal' ),
'c8' => array( 'model' => 'c5',
'items' => array( 'integrated_search_field5',
'search_field_between' ),
'orientation' => 'horizontal' ),
'c9' => array( 'model' => 'c5',
'items' => array( 'search_field_options1' ) ),
'c10' => array( 'model' => 'c3',
'items' => array( 'search_field_options2' ) ),
'c11' => array( 'model' => 'c5',
'items' => array( 'search_field_options' ) ),
'c1' => array( 'model' => 'c5',
'items' => array( 'search_field_label' ),
'useFullWidth' => true ) ),
'deferredItems' => array(  ),
'separateLabels' => false ) ),
'items' => array( 'search_header' => array( 'type' => 'search_header',
'title' => array( 'page' => 'search',
'table' => 'SOA_CIS_view1',
'type' => 7 ) ),
'search_reset' => array( 'type' => 'search_reset' ),
'search_back_list' => array( 'type' => 'search_back_list' ),
'search_search' => array( 'type' => 'search_search' ),
'search_cancel' => array( 'type' => 'search_cancel' ),
'integrated_search_field' => array( 'field' => 'NOPROPOSAL',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true,
'width' => '200px' ),
'integrated_search_field1' => array( 'field' => 'KODEKC',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'label' => array( 'field' => 'KODEKC',
'table' => 'SOA_CIS_view',
'type' => 3 ),
'joined' => false,
'separated' => true,
'width' => '200px' ),
'integrated_search_field5' => array( 'field' => 'AWAL',
'type' => 'search_field',
'orientation' => 0,
'required' => false,
'joined' => false,
'separated' => true,
'width' => '200px' ),
'search_field_label' => array( 'type' => 'search_field_label',
'field' => 'AWAL',
'separated' => true ),
'search_field_options' => array( 'type' => 'search_field_options',
'field' => 'AWAL',
'separated' => true ),
'search_field_between' => array( 'type' => 'search_field_between',
'field' => 'AWAL',
'separated' => true ),
'search_field_label1' => array( 'type' => 'search_field_label',
'field' => 'NOPROPOSAL',
'separated' => true ),
'search_field_options1' => array( 'type' => 'search_field_options',
'field' => 'NOPROPOSAL',
'separated' => true ),
'search_field_between1' => array( 'type' => 'search_field_between',
'field' => 'NOPROPOSAL',
'separated' => true ),
'search_field_label2' => array( 'type' => 'search_field_label',
'field' => 'KODEKC',
'separated' => true ),
'search_field_options2' => array( 'type' => 'search_field_options',
'field' => 'KODEKC',
'separated' => true ),
'search_field_between2' => array( 'type' => 'search_field_between',
'field' => 'KODEKC',
'separated' => true ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>