<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array( 'IDCIT',
'CIT_REGDATE',
'CIT_IDCBG',
'CIT_MTU',
'CIT_TTG',
'CIT_DATE_DEPART',
'CIT_DATE_ARRIV',
'CIT_EMP_NAMA',
'CIT_SEC_NAMA',
'CIT_VECH',
'CIT_NUMBER',
'CIT_ADD_USER',
'CIT_ADD_DATE',
'CIT_EDIT_USER',
'CIT_EDIT_DATE',
'CIT_TSI',
'CIT_FL',
'CIT_ASAL',
'CIT_TUJUAN',
'CIT_TOKEN',
'CIT_BSMID',
'CIT_PROPOSAL',
'CIT_PREMI',
'CIT_PERIODE_END',
'CIT_APP_USER',
'CIT_APP_DATE',
'CIT_APP_NOTE',
'CIT_APP_FL',
'CIT_TO_USER',
'CIT_TO_DATE',
'CIT_RATE',
'CIT_LIMIT',
'IS_OL' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'IDCIT' => array( 'import_field' ),
'CIT_REGDATE' => array( 'import_field1' ),
'CIT_IDCBG' => array( 'import_field2' ),
'CIT_MTU' => array( 'import_field3' ),
'CIT_TTG' => array( 'import_field4' ),
'CIT_DATE_DEPART' => array( 'import_field5' ),
'CIT_DATE_ARRIV' => array( 'import_field6' ),
'CIT_EMP_NAMA' => array( 'import_field7' ),
'CIT_SEC_NAMA' => array( 'import_field8' ),
'CIT_VECH' => array( 'import_field9' ),
'CIT_NUMBER' => array( 'import_field10' ),
'CIT_ADD_USER' => array( 'import_field11' ),
'CIT_ADD_DATE' => array( 'import_field12' ),
'CIT_EDIT_USER' => array( 'import_field13' ),
'CIT_EDIT_DATE' => array( 'import_field14' ),
'CIT_TSI' => array( 'import_field15' ),
'CIT_FL' => array( 'import_field16' ),
'CIT_ASAL' => array( 'import_field17' ),
'CIT_TUJUAN' => array( 'import_field18' ),
'CIT_TOKEN' => array( 'import_field19' ),
'CIT_BSMID' => array( 'import_field20' ),
'CIT_PROPOSAL' => array( 'import_field21' ),
'CIT_PREMI' => array( 'import_field22' ),
'CIT_PERIODE_END' => array( 'import_field23' ),
'CIT_APP_USER' => array( 'import_field24' ),
'CIT_APP_DATE' => array( 'import_field25' ),
'CIT_APP_NOTE' => array( 'import_field26' ),
'CIT_APP_FL' => array( 'import_field27' ),
'CIT_TO_USER' => array( 'import_field28' ),
'CIT_TO_DATE' => array( 'import_field29' ),
'CIT_RATE' => array( 'import_field30' ),
'CIT_LIMIT' => array( 'import_field31' ),
'IS_OL' => array( 'import_field32' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'import_header' ),
'grid' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'import_header' => 'top',
'import_field' => 'grid',
'import_field1' => 'grid',
'import_field2' => 'grid',
'import_field3' => 'grid',
'import_field4' => 'grid',
'import_field5' => 'grid',
'import_field6' => 'grid',
'import_field7' => 'grid',
'import_field8' => 'grid',
'import_field9' => 'grid',
'import_field10' => 'grid',
'import_field11' => 'grid',
'import_field12' => 'grid',
'import_field13' => 'grid',
'import_field14' => 'grid',
'import_field15' => 'grid',
'import_field16' => 'grid',
'import_field17' => 'grid',
'import_field18' => 'grid',
'import_field19' => 'grid',
'import_field20' => 'grid',
'import_field21' => 'grid',
'import_field22' => 'grid',
'import_field23' => 'grid',
'import_field24' => 'grid',
'import_field25' => 'grid',
'import_field26' => 'grid',
'import_field27' => 'grid',
'import_field28' => 'grid',
'import_field29' => 'grid',
'import_field30' => 'grid',
'import_field31' => 'grid',
'import_field32' => 'grid' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'import_header' => array( 'import_header' ),
'import_field' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ) );
			$pageArray = array( 'id' => 'import',
'type' => 'import',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'import-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'import-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'import_field',
'import_field1',
'import_field2',
'import_field3',
'import_field4',
'import_field5',
'import_field6',
'import_field7',
'import_field8',
'import_field9',
'import_field10',
'import_field11',
'import_field12',
'import_field13',
'import_field14',
'import_field15',
'import_field16',
'import_field17',
'import_field18',
'import_field19',
'import_field20',
'import_field21',
'import_field22',
'import_field23',
'import_field24',
'import_field25',
'import_field26',
'import_field27',
'import_field28',
'import_field29',
'import_field30',
'import_field31',
'import_field32' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'import_header' => array( 'type' => 'import_header' ),
'import_field' => array( 'field' => 'IDCIT',
'type' => 'import_field' ),
'import_field1' => array( 'field' => 'CIT_REGDATE',
'type' => 'import_field' ),
'import_field2' => array( 'field' => 'CIT_IDCBG',
'type' => 'import_field' ),
'import_field3' => array( 'field' => 'CIT_MTU',
'type' => 'import_field' ),
'import_field4' => array( 'field' => 'CIT_TTG',
'type' => 'import_field' ),
'import_field5' => array( 'field' => 'CIT_DATE_DEPART',
'type' => 'import_field' ),
'import_field6' => array( 'field' => 'CIT_DATE_ARRIV',
'type' => 'import_field' ),
'import_field7' => array( 'field' => 'CIT_EMP_NAMA',
'type' => 'import_field' ),
'import_field8' => array( 'field' => 'CIT_SEC_NAMA',
'type' => 'import_field' ),
'import_field9' => array( 'field' => 'CIT_VECH',
'type' => 'import_field' ),
'import_field10' => array( 'field' => 'CIT_NUMBER',
'type' => 'import_field' ),
'import_field11' => array( 'field' => 'CIT_ADD_USER',
'type' => 'import_field' ),
'import_field12' => array( 'field' => 'CIT_ADD_DATE',
'type' => 'import_field' ),
'import_field13' => array( 'field' => 'CIT_EDIT_USER',
'type' => 'import_field' ),
'import_field14' => array( 'field' => 'CIT_EDIT_DATE',
'type' => 'import_field' ),
'import_field15' => array( 'field' => 'CIT_TSI',
'type' => 'import_field' ),
'import_field16' => array( 'field' => 'CIT_FL',
'type' => 'import_field' ),
'import_field17' => array( 'field' => 'CIT_ASAL',
'type' => 'import_field' ),
'import_field18' => array( 'field' => 'CIT_TUJUAN',
'type' => 'import_field' ),
'import_field19' => array( 'field' => 'CIT_TOKEN',
'type' => 'import_field' ),
'import_field20' => array( 'field' => 'CIT_BSMID',
'type' => 'import_field' ),
'import_field21' => array( 'field' => 'CIT_PROPOSAL',
'type' => 'import_field' ),
'import_field22' => array( 'field' => 'CIT_PREMI',
'type' => 'import_field' ),
'import_field23' => array( 'field' => 'CIT_PERIODE_END',
'type' => 'import_field' ),
'import_field24' => array( 'field' => 'CIT_APP_USER',
'type' => 'import_field' ),
'import_field25' => array( 'field' => 'CIT_APP_DATE',
'type' => 'import_field' ),
'import_field26' => array( 'field' => 'CIT_APP_NOTE',
'type' => 'import_field' ),
'import_field27' => array( 'field' => 'CIT_APP_FL',
'type' => 'import_field' ),
'import_field28' => array( 'field' => 'CIT_TO_USER',
'type' => 'import_field' ),
'import_field29' => array( 'field' => 'CIT_TO_DATE',
'type' => 'import_field' ),
'import_field30' => array( 'field' => 'CIT_RATE',
'type' => 'import_field' ),
'import_field31' => array( 'field' => 'CIT_LIMIT',
'type' => 'import_field' ),
'import_field32' => array( 'field' => 'IS_OL',
'type' => 'import_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>