<?php
			$optionsArray = array( 'details' => array( 'TEMBSICITASAL_verifikasi' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ),
'TEMPBSICIT_APPRV' => array( 'displayPreview' => 1,
'previewPageId' => 'list' ) ),
'captcha' => array( 'captcha' => false ),
'fields' => array( 'gridFields' => array( 'CIT_REGDATE',
'CIT_IDCBG',
'CIT_TTG',
'CIT_DATE_DEPART',
'CIT_DATE_ARRIV',
'CIT_EMP_NAMA',
'CIT_SEC_NAMA',
'CIT_VECH',
'CIT_NUMBER',
'CIT_TSI',
'CIT_FL',
'CIT_LIMIT',
'IS_OL' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'updateOnEditFields' => array(  ),
'fieldItems' => array( 'CIT_REGDATE' => array( 'integrated_edit_field' ),
'CIT_IDCBG' => array( 'integrated_edit_field1' ),
'CIT_TTG' => array( 'integrated_edit_field3' ),
'CIT_DATE_DEPART' => array( 'integrated_edit_field4' ),
'CIT_DATE_ARRIV' => array( 'integrated_edit_field5' ),
'CIT_EMP_NAMA' => array( 'integrated_edit_field6' ),
'CIT_SEC_NAMA' => array( 'integrated_edit_field7' ),
'CIT_VECH' => array( 'integrated_edit_field8' ),
'CIT_NUMBER' => array( 'integrated_edit_field9' ),
'CIT_TSI' => array( 'integrated_edit_field2' ),
'CIT_FL' => array( 'integrated_edit_field10' ),
'CIT_LIMIT' => array( 'integrated_edit_field11' ),
'IS_OL' => array( 'integrated_edit_field12' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'edit_message' ),
'below-grid' => array( 'edit_back_list',
'edit_close' ),
'supertop' => array( 'logo',
'menu',
'notifications',
'loginform_login',
'username_button' ),
'top' => array(  ),
'grid' => array( 'section',
'section1',
'section2',
'section4' ),
'section' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field3' ),
'section1' => array( 'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field2',
'integrated_edit_field11',
'integrated_edit_field10',
'integrated_edit_field12' ),
'section2' => array( 'details_preview' ),
'section4' => array( 'details_preview1' ) ),
'formXtTags' => array( 'above-grid' => array( 'message_block' ),
'below-grid' => array( 'back_button',
'close_button' ),
'top' => array(  ) ),
'itemForms' => array( 'edit_message' => 'above-grid',
'edit_back_list' => 'below-grid',
'edit_close' => 'below-grid',
'logo' => 'supertop',
'menu' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'section' => 'grid',
'section1' => 'grid',
'section2' => 'grid',
'section4' => 'grid',
'integrated_edit_field' => 'section',
'integrated_edit_field1' => 'section',
'integrated_edit_field3' => 'section',
'integrated_edit_field4' => 'section1',
'integrated_edit_field5' => 'section1',
'integrated_edit_field8' => 'section1',
'integrated_edit_field9' => 'section1',
'integrated_edit_field6' => 'section1',
'integrated_edit_field7' => 'section1',
'integrated_edit_field2' => 'section1',
'integrated_edit_field11' => 'section1',
'integrated_edit_field10' => 'section1',
'integrated_edit_field12' => 'section1',
'details_preview' => 'section2',
'details_preview1' => 'section4' ),
'itemLocations' => array( 'section' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section1' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section2' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'section4' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'integrated_edit_field' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field1' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field3' => array( 'location' => 'section',
'cellId' => 'c2' ),
'integrated_edit_field4' => array( 'location' => 'section1',
'cellId' => 'c1' ),
'integrated_edit_field5' => array( 'location' => 'section1',
'cellId' => 'c' ),
'integrated_edit_field8' => array( 'location' => 'section1',
'cellId' => 'c2' ),
'integrated_edit_field9' => array( 'location' => 'section1',
'cellId' => 'c3' ),
'integrated_edit_field6' => array( 'location' => 'section1',
'cellId' => 'c4' ),
'integrated_edit_field7' => array( 'location' => 'section1',
'cellId' => 'c5' ),
'integrated_edit_field2' => array( 'location' => 'section1',
'cellId' => 'c6' ),
'integrated_edit_field11' => array( 'location' => 'section1',
'cellId' => 'c7' ),
'integrated_edit_field10' => array( 'location' => 'section1',
'cellId' => 'c9' ),
'integrated_edit_field12' => array( 'location' => 'section1',
'cellId' => 'c10' ),
'details_preview' => array( 'location' => 'section2',
'cellId' => 'c1' ),
'details_preview1' => array( 'location' => 'section4',
'cellId' => 'c1' ) ),
'itemVisiblity' => array( 'menu' => 3,
'username_button' => 3,
'loginform_login' => 3 ) ),
'itemsByType' => array( 'edit_message' => array( 'edit_message' ),
'edit_back_list' => array( 'edit_back_list' ),
'edit_close' => array( 'edit_close' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'integrated_edit_field' => array( 'integrated_edit_field',
'integrated_edit_field1',
'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field6',
'integrated_edit_field7',
'integrated_edit_field8',
'integrated_edit_field9',
'integrated_edit_field2',
'integrated_edit_field10',
'integrated_edit_field11',
'integrated_edit_field12' ),
'notifications' => array( 'notifications' ),
'details_preview' => array( 'details_preview',
'details_preview1' ),
'section' => array( 'section',
'section1',
'section2',
'section4' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section',
'section1',
'section2',
'section4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 2 ),
'section1' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field5' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field6' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c5' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field7' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field8' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 1 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field9' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c6' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c7' => array( 'cols' => array( 1 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field11' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c8' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array(  ),
'fixedAtServer' => false,
'fixedAtClient' => false ),
'c9' => array( 'cols' => array( 1 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field10' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c10' => array( 'cols' => array( 0,
1 ),
'rows' => array( 5 ),
'tags' => array(  ),
'items' => array( 'integrated_edit_field12' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 2,
'height' => 6 ),
'section2' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section4' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'details_preview1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'edit',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'edit' => array( 'updateSelected' => false ) );
			$pageArray = array( 'id' => 'edit',
'type' => 'edit',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'edit-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_message' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'edit-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'edit_back_list',
'edit_close' ) ),
'c2' => array( 'model' => 'c2',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'topbar-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'menu' ) ),
'c3' => array( 'model' => 'c3',
'items' => array( 'notifications',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'edit-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'section',
'section1',
'section2',
'section4' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field1' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field3' ) ),
'c3' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section1' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c6' ),
array( 'cell' => 'c7' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c8' ),
array( 'cell' => 'c9' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field4' ) ),
'c' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field5' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field8' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field9' ) ),
'c4' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field6' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field7' ) ),
'c6' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field2' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field11' ) ),
'c8' => array( 'model' => 'c1',
'items' => array(  ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field10' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'integrated_edit_field12' ),
'align' => 'center' ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section2' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section4' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'details_preview1' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'edit_message' => array( 'type' => 'edit_message' ),
'edit_back_list' => array( 'type' => 'edit_back_list' ),
'edit_close' => array( 'type' => 'edit_close' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'integrated_edit_field' => array( 'field' => 'CIT_REGDATE',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field1' => array( 'field' => 'CIT_IDCBG',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field3' => array( 'field' => 'CIT_TTG',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field4' => array( 'field' => 'CIT_DATE_DEPART',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field5' => array( 'field' => 'CIT_DATE_ARRIV',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field6' => array( 'field' => 'CIT_EMP_NAMA',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field7' => array( 'field' => 'CIT_SEC_NAMA',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field8' => array( 'field' => 'CIT_VECH',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field9' => array( 'field' => 'CIT_NUMBER',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'notifications' => array( 'type' => 'notifications' ),
'details_preview' => array( 'type' => 'details_preview',
'table' => 'TEMBSICITASAL_verifikasi',
'items' => array(  ),
'popup' => false,
'pageId' => 'list',
'caption' => array( 'page' => 'list',
'table' => 'TEMBSICITASAL_verifikasi',
'type' => 7 ) ),
'section' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Cash In Transit' ),
'location' => 'section',
'bsStyle' => 'default',
'panelType' => 3 ),
'section1' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => '' ),
'location' => 'section1',
'bsStyle' => 'default',
'panelType' => 3 ),
'section2' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Informasi Tambahan (Asal dan Tujuan)' ),
'location' => 'section2',
'bsStyle' => 'default',
'panelType' => 3 ),
'details_preview1' => array( 'type' => 'details_preview',
'table' => 'TEMPBSICIT_APPRV',
'items' => array(  ),
'popup' => false,
'pageId' => 'list' ),
'integrated_edit_field2' => array( 'field' => 'CIT_TSI',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field10' => array( 'field' => 'CIT_FL',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field11' => array( 'field' => 'CIT_LIMIT',
'type' => 'integrated_edit_field',
'orientation' => 0,
'updateOnEdit' => false ),
'integrated_edit_field12' => array( 'field' => 'IS_OL',
'type' => 'integrated_edit_field',
'orientation' => 0,
'label' => array( 'field' => 'IS_OL',
'table' => 'TEMPBSICIT_verifikasi',
'type' => 3 ),
'background' => '#ff0000',
'color' => '#ffffff',
'bold' => true,
'font-size' => '18px' ),
'section4' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => '' ),
'location' => 'section4',
'bsStyle' => 'default',
'panelType' => 3 ) ),
'dbProps' => array(  ),
'version' => 11,
'pageWidth' => 'full',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>