<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'fields' => array( 'gridFields' => array( 'KODECABANG',
'DATE',
'SUMINSURED',
'CIS_FL',
'CIS_TIPE' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'KODECABANG' => array( 'integrated_edit_field3',
'edit_field_label',
'edit_field_tooltip' ),
'DATE' => array( 'integrated_edit_field4',
'edit_field_label1',
'edit_field_tooltip1' ),
'SUMINSURED' => array( 'integrated_edit_field5',
'edit_field_label2',
'edit_field_tooltip2' ),
'CIS_FL' => array( 'integrated_edit_field8',
'edit_field_label3',
'edit_field_tooltip3' ),
'CIS_TIPE' => array( 'integrated_edit_field15',
'edit_field_label4',
'edit_field_tooltip4' ) ) ),
'pageLinks' => array( 'edit' => true,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array(  ),
'below-grid' => array( 'view_back_list',
'view_close',
'custom_button',
'hamburger' ),
'supertop' => array( 'logo',
'menu',
'notifications',
'loginform_login',
'username_button' ),
'top' => array(  ),
'grid' => array( 'section' ),
'section' => array( 'edit_field_label',
'integrated_edit_field3',
'edit_field_tooltip',
'edit_field_label1',
'integrated_edit_field4',
'edit_field_tooltip1',
'edit_field_label2',
'integrated_edit_field5',
'edit_field_tooltip2',
'edit_field_label3',
'integrated_edit_field8',
'edit_field_tooltip3',
'edit_field_label4',
'integrated_edit_field15',
'edit_field_tooltip4' ) ),
'formXtTags' => array( 'above-grid' => array(  ),
'top' => array(  ) ),
'itemForms' => array( 'view_back_list' => 'below-grid',
'view_close' => 'below-grid',
'custom_button' => 'below-grid',
'hamburger' => 'below-grid',
'logo' => 'supertop',
'menu' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'section' => 'grid',
'edit_field_label' => 'section',
'integrated_edit_field3' => 'section',
'edit_field_tooltip' => 'section',
'edit_field_label1' => 'section',
'integrated_edit_field4' => 'section',
'edit_field_tooltip1' => 'section',
'edit_field_label2' => 'section',
'integrated_edit_field5' => 'section',
'edit_field_tooltip2' => 'section',
'edit_field_label3' => 'section',
'integrated_edit_field8' => 'section',
'edit_field_tooltip3' => 'section',
'edit_field_label4' => 'section',
'integrated_edit_field15' => 'section',
'edit_field_tooltip4' => 'section' ),
'itemLocations' => array( 'section' => array( 'location' => 'grid',
'cellId' => 'c3' ),
'edit_field_label' => array( 'location' => 'section',
'cellId' => 'c1' ),
'integrated_edit_field3' => array( 'location' => 'section',
'cellId' => 'c1' ),
'edit_field_tooltip' => array( 'location' => 'section',
'cellId' => 'c1' ),
'edit_field_label1' => array( 'location' => 'section',
'cellId' => 'c' ),
'integrated_edit_field4' => array( 'location' => 'section',
'cellId' => 'c' ),
'edit_field_tooltip1' => array( 'location' => 'section',
'cellId' => 'c' ),
'edit_field_label2' => array( 'location' => 'section',
'cellId' => 'c2' ),
'integrated_edit_field5' => array( 'location' => 'section',
'cellId' => 'c2' ),
'edit_field_tooltip2' => array( 'location' => 'section',
'cellId' => 'c2' ),
'edit_field_label3' => array( 'location' => 'section',
'cellId' => 'c3' ),
'integrated_edit_field8' => array( 'location' => 'section',
'cellId' => 'c3' ),
'edit_field_tooltip3' => array( 'location' => 'section',
'cellId' => 'c3' ),
'edit_field_label4' => array( 'location' => 'section',
'cellId' => 'c4' ),
'integrated_edit_field15' => array( 'location' => 'section',
'cellId' => 'c4' ),
'edit_field_tooltip4' => array( 'location' => 'section',
'cellId' => 'c4' ) ),
'itemVisiblity' => array( 'menu' => 3,
'username_button' => 3,
'loginform_login' => 3 ) ),
'itemsByType' => array( 'view_back_list' => array( 'view_back_list' ),
'view_close' => array( 'view_close' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'notifications' => array( 'notifications' ),
'hamburger' => array( 'hamburger' ),
'view_edit' => array( 'view_edit' ),
'edit_field' => array( 'integrated_edit_field3',
'integrated_edit_field4',
'integrated_edit_field5',
'integrated_edit_field8',
'integrated_edit_field15' ),
'section' => array( 'section' ),
'custom_button' => array( 'custom_button' ),
'edit_field_label' => array( 'edit_field_label',
'edit_field_label1',
'edit_field_label2',
'edit_field_label3',
'edit_field_label4' ),
'edit_field_tooltip' => array( 'edit_field_tooltip',
'edit_field_tooltip1',
'edit_field_tooltip2',
'edit_field_tooltip3',
'edit_field_tooltip4' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'c3' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'section' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 1 ),
'section' => array( 'cells' => array( 'c1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'edit_field_label',
'integrated_edit_field3',
'edit_field_tooltip' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'edit_field_label1',
'integrated_edit_field4',
'edit_field_tooltip1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c2' => array( 'cols' => array( 0 ),
'rows' => array( 2 ),
'tags' => array(  ),
'items' => array( 'edit_field_label2',
'integrated_edit_field5',
'edit_field_tooltip2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c3' => array( 'cols' => array( 0 ),
'rows' => array( 3 ),
'tags' => array(  ),
'items' => array( 'edit_field_label3',
'integrated_edit_field8',
'edit_field_tooltip3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'c4' => array( 'cols' => array( 0 ),
'rows' => array( 4 ),
'tags' => array(  ),
'items' => array( 'edit_field_label4',
'integrated_edit_field15',
'edit_field_tooltip4' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 1,
'height' => 5 ) ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => true,
'customButtons' => array( 'btn_approve' ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'view',
'breadcrumb' => false,
'nextPrev' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array( 'btn_approve' ) ) );
			$pageArray = array( 'id' => 'view',
'type' => 'view',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'view-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 2 ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'view-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'view_back_list',
'view_close',
'custom_button' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'hamburger' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'topbar-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'menu' ) ),
'c3' => array( 'model' => 'c3',
'items' => array( 'notifications',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'view-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c3' ) ),
'section' => '' ) ),
'cells' => array( 'c3' => array( 'model' => 'c3',
'items' => array( 'section' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ),
'section' => array( 'modelId' => 'simple-edit',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c3' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c4' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c3',
'items' => array( 'edit_field_label',
'integrated_edit_field3',
'edit_field_tooltip' ) ),
'c' => array( 'model' => 'c3',
'items' => array( 'edit_field_label1',
'integrated_edit_field4',
'edit_field_tooltip1' ) ),
'c2' => array( 'model' => 'c3',
'items' => array( 'edit_field_label2',
'integrated_edit_field5',
'edit_field_tooltip2' ) ),
'c3' => array( 'model' => 'c3',
'items' => array( 'edit_field_label3',
'integrated_edit_field8',
'edit_field_tooltip3' ) ),
'c4' => array( 'model' => 'c3',
'items' => array( 'edit_field_label4',
'integrated_edit_field15',
'edit_field_tooltip4' ) ) ),
'deferredItems' => array(  ),
'columnCount' => 1,
'inlineLabels' => false,
'separateLabels' => false ) ),
'items' => array( 'view_back_list' => array( 'type' => 'view_back_list' ),
'view_close' => array( 'type' => 'view_close' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'notifications' => array( 'type' => 'notifications' ),
'hamburger' => array( 'type' => 'hamburger',
'items' => array( 'view_edit' ) ),
'view_edit' => array( 'type' => 'view_edit' ),
'integrated_edit_field3' => array( 'field' => 'KODECABANG',
'type' => 'edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'joined' => false,
'separated' => true ),
'integrated_edit_field4' => array( 'field' => 'DATE',
'type' => 'edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'joined' => false,
'separated' => true ),
'integrated_edit_field5' => array( 'field' => 'SUMINSURED',
'type' => 'edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'joined' => false,
'separated' => true ),
'integrated_edit_field8' => array( 'field' => 'CIS_FL',
'type' => 'edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'joined' => false,
'separated' => true ),
'integrated_edit_field15' => array( 'field' => 'CIS_TIPE',
'type' => 'edit_field',
'orientation' => 0,
'updateOnEdit' => false,
'joined' => false,
'separated' => true ),
'section' => array( 'type' => 'section',
'title' => array( 'type' => 0,
'text' => 'Data CIS Overlimit' ),
'location' => 'section',
'bsStyle' => 'default',
'panelType' => 3 ),
'custom_button' => array( 'eventId' => 'btn_approve',
'label' => array( 'text' => 'Approve',
'type' => 0 ),
'type' => 'custom_button',
'buttonStyle' => 'success' ),
'edit_field_label' => array( 'type' => 'edit_field_label',
'field' => 'KODECABANG',
'separated' => true,
'bold' => true,
'label' => array( 'field' => 'KODECABANG',
'table' => 'TEMPBSICIS_OL',
'type' => 3 ) ),
'edit_field_tooltip' => array( 'type' => 'edit_field_tooltip',
'field' => 'KODECABANG',
'separated' => true ),
'edit_field_label1' => array( 'type' => 'edit_field_label',
'field' => 'DATE',
'separated' => true,
'bold' => true,
'label' => array( 'field' => 'DATE',
'table' => 'TEMPBSICIS_OL',
'type' => 3 ) ),
'edit_field_tooltip1' => array( 'type' => 'edit_field_tooltip',
'field' => 'DATE',
'separated' => true ),
'edit_field_label2' => array( 'type' => 'edit_field_label',
'field' => 'SUMINSURED',
'separated' => true,
'bold' => true,
'label' => array( 'field' => 'SUMINSURED',
'table' => 'TEMPBSICIS_OL',
'type' => 3 ) ),
'edit_field_tooltip2' => array( 'type' => 'edit_field_tooltip',
'field' => 'SUMINSURED',
'separated' => true ),
'edit_field_label3' => array( 'type' => 'edit_field_label',
'field' => 'CIS_FL',
'separated' => true,
'bold' => true,
'label' => array( 'field' => 'CIS_FL',
'table' => 'TEMPBSICIS_OL',
'type' => 3 ) ),
'edit_field_tooltip3' => array( 'type' => 'edit_field_tooltip',
'field' => 'CIS_FL',
'separated' => true ),
'edit_field_label4' => array( 'type' => 'edit_field_label',
'field' => 'CIS_TIPE',
'separated' => true,
'bold' => true,
'label' => array( 'field' => 'CIS_TIPE',
'table' => 'TEMPBSICIS_OL',
'type' => 3 ) ),
'edit_field_tooltip4' => array( 'type' => 'edit_field_tooltip',
'field' => 'CIS_TIPE',
'separated' => true ) ),
'dbProps' => array(  ),
'version' => 11,
'pageWidth' => 'full',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>