<?php
			$optionsArray = array( 'totals' => array( 'IDCIT' => array( 'totalsType' => '' ),
'CIT_REGDATE' => array( 'totalsType' => '' ),
'CIT_IDCBG' => array( 'totalsType' => '' ),
'CIT_MTU' => array( 'totalsType' => '' ),
'CIT_TTG' => array( 'totalsType' => '' ),
'CIT_DATE_DEPART' => array( 'totalsType' => '' ),
'CIT_DATE_ARRIV' => array( 'totalsType' => '' ),
'CIT_EMP_NAMA' => array( 'totalsType' => '' ),
'CIT_SEC_NAMA' => array( 'totalsType' => '' ),
'CIT_VECH' => array( 'totalsType' => '' ),
'CIT_NUMBER' => array( 'totalsType' => '' ),
'CIT_ADD_USER' => array( 'totalsType' => '' ),
'CIT_ADD_DATE' => array( 'totalsType' => '' ),
'CIT_EDIT_USER' => array( 'totalsType' => '' ),
'CIT_EDIT_DATE' => array( 'totalsType' => '' ),
'CIT_TSI' => array( 'totalsType' => '' ),
'CIT_FL' => array( 'totalsType' => '' ),
'CIT_ASAL' => array( 'totalsType' => '' ),
'CIT_TUJUAN' => array( 'totalsType' => '' ),
'CIT_TOKEN' => array( 'totalsType' => '' ),
'CIT_BSMID' => array( 'totalsType' => '' ),
'CIT_PROPOSAL' => array( 'totalsType' => '' ),
'CIT_PREMI' => array( 'totalsType' => '' ),
'CIT_PERIODE_END' => array( 'totalsType' => '' ),
'CIT_APP_USER' => array( 'totalsType' => '' ),
'CIT_APP_DATE' => array( 'totalsType' => '' ),
'CIT_APP_NOTE' => array( 'totalsType' => '' ),
'CIT_APP_FL' => array( 'totalsType' => '' ),
'CIT_TO_USER' => array( 'totalsType' => '' ),
'CIT_TO_DATE' => array( 'totalsType' => '' ) ),
'fields' => array( 'gridFields' => array( 'IDCIT',
'CIT_REGDATE',
'CIT_IDCBG',
'CIT_MTU',
'CIT_TTG',
'CIT_DATE_DEPART',
'CIT_DATE_ARRIV',
'CIT_EMP_NAMA',
'CIT_SEC_NAMA',
'CIT_VECH',
'CIT_NUMBER',
'CIT_ADD_USER',
'CIT_ADD_DATE',
'CIT_EDIT_USER',
'CIT_EDIT_DATE',
'CIT_TSI',
'CIT_FL',
'CIT_ASAL',
'CIT_TUJUAN',
'CIT_TOKEN' ),
'exportFields' => array( 'IDCIT',
'CIT_REGDATE',
'CIT_IDCBG',
'CIT_MTU',
'CIT_TTG',
'CIT_DATE_DEPART',
'CIT_DATE_ARRIV',
'CIT_EMP_NAMA',
'CIT_SEC_NAMA',
'CIT_VECH',
'CIT_NUMBER',
'CIT_ADD_USER',
'CIT_ADD_DATE',
'CIT_EDIT_USER',
'CIT_EDIT_DATE',
'CIT_TSI',
'CIT_FL',
'CIT_ASAL',
'CIT_TUJUAN',
'CIT_TOKEN' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'IDCIT' => array( 'export_field' ),
'CIT_REGDATE' => array( 'export_field1' ),
'CIT_IDCBG' => array( 'export_field2' ),
'CIT_MTU' => array( 'export_field3' ),
'CIT_TTG' => array( 'export_field4' ),
'CIT_DATE_DEPART' => array( 'export_field5' ),
'CIT_DATE_ARRIV' => array( 'export_field6' ),
'CIT_EMP_NAMA' => array( 'export_field7' ),
'CIT_SEC_NAMA' => array( 'export_field8' ),
'CIT_VECH' => array( 'export_field9' ),
'CIT_NUMBER' => array( 'export_field10' ),
'CIT_ADD_USER' => array( 'export_field11' ),
'CIT_ADD_DATE' => array( 'export_field12' ),
'CIT_EDIT_USER' => array( 'export_field13' ),
'CIT_EDIT_DATE' => array( 'export_field14' ),
'CIT_TSI' => array( 'export_field15' ),
'CIT_FL' => array( 'export_field16' ),
'CIT_ASAL' => array( 'export_field17' ),
'CIT_TUJUAN' => array( 'export_field18' ),
'CIT_TOKEN' => array( 'export_field19' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'supertop' => array(  ),
'top' => array( 'export_header' ),
'grid' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19' ),
'footer' => array( 'export_export',
'export_cancel' ) ),
'formXtTags' => array( 'supertop' => array(  ) ),
'itemForms' => array( 'export_header' => 'top',
'export_field' => 'grid',
'export_field1' => 'grid',
'export_field2' => 'grid',
'export_field3' => 'grid',
'export_field4' => 'grid',
'export_field5' => 'grid',
'export_field6' => 'grid',
'export_field7' => 'grid',
'export_field8' => 'grid',
'export_field9' => 'grid',
'export_field10' => 'grid',
'export_field11' => 'grid',
'export_field12' => 'grid',
'export_field13' => 'grid',
'export_field14' => 'grid',
'export_field15' => 'grid',
'export_field16' => 'grid',
'export_field17' => 'grid',
'export_field18' => 'grid',
'export_field19' => 'grid',
'export_export' => 'footer',
'export_cancel' => 'footer' ),
'itemLocations' => array(  ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'export_header' => array( 'export_header' ),
'export_export' => array( 'export_export' ),
'export_cancel' => array( 'export_cancel' ),
'export_field' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'export' => array( 'format' => 2,
'selectFields' => false,
'delimiter' => ',',
'selectDelimiter' => false,
'exportFileTypes' => array( 'excel' => true,
'word' => true,
'csv' => true,
'xml' => false ) ) );
			$pageArray = array( 'id' => 'export',
'type' => 'export',
'layoutId' => 'first',
'disabled' => 0,
'default' => 0,
'forms' => array( 'supertop' => array( 'modelId' => 'panel-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'export-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_header' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'export-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'export_field',
'export_field1',
'export_field2',
'export_field3',
'export_field4',
'export_field5',
'export_field6',
'export_field7',
'export_field8',
'export_field9',
'export_field10',
'export_field11',
'export_field12',
'export_field13',
'export_field14',
'export_field15',
'export_field16',
'export_field17',
'export_field18',
'export_field19' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'footer' => array( 'modelId' => 'export-footer',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'export_export',
'export_cancel' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'export_header' => array( 'type' => 'export_header' ),
'export_export' => array( 'type' => 'export_export' ),
'export_cancel' => array( 'type' => 'export_cancel' ),
'export_field' => array( 'field' => 'IDCIT',
'type' => 'export_field' ),
'export_field1' => array( 'field' => 'CIT_REGDATE',
'type' => 'export_field' ),
'export_field2' => array( 'field' => 'CIT_IDCBG',
'type' => 'export_field' ),
'export_field3' => array( 'field' => 'CIT_MTU',
'type' => 'export_field' ),
'export_field4' => array( 'field' => 'CIT_TTG',
'type' => 'export_field' ),
'export_field5' => array( 'field' => 'CIT_DATE_DEPART',
'type' => 'export_field' ),
'export_field6' => array( 'field' => 'CIT_DATE_ARRIV',
'type' => 'export_field' ),
'export_field7' => array( 'field' => 'CIT_EMP_NAMA',
'type' => 'export_field' ),
'export_field8' => array( 'field' => 'CIT_SEC_NAMA',
'type' => 'export_field' ),
'export_field9' => array( 'field' => 'CIT_VECH',
'type' => 'export_field' ),
'export_field10' => array( 'field' => 'CIT_NUMBER',
'type' => 'export_field' ),
'export_field11' => array( 'field' => 'CIT_ADD_USER',
'type' => 'export_field' ),
'export_field12' => array( 'field' => 'CIT_ADD_DATE',
'type' => 'export_field' ),
'export_field13' => array( 'field' => 'CIT_EDIT_USER',
'type' => 'export_field' ),
'export_field14' => array( 'field' => 'CIT_EDIT_DATE',
'type' => 'export_field' ),
'export_field15' => array( 'field' => 'CIT_TSI',
'type' => 'export_field' ),
'export_field16' => array( 'field' => 'CIT_FL',
'type' => 'export_field' ),
'export_field17' => array( 'field' => 'CIT_ASAL',
'type' => 'export_field' ),
'export_field18' => array( 'field' => 'CIT_TUJUAN',
'type' => 'export_field' ),
'export_field19' => array( 'field' => 'CIT_TOKEN',
'type' => 'export_field' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right',
'exportFormat' => 2,
'exportDelimiter' => ',',
'exportSelectDelimiter' => false,
'exportSelectFields' => false );
		?>