<?php
			$optionsArray = array( 'pdf' => array( 'pdfView' => false ),
'fields' => array( 'gridFields' => array( 'DATE',
'KODECABANG',
'SUMINSURED' ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array( 'DATE' => array( 'report_advanced_field1',
'report_advanced_field_label1' ),
'KODECABANG' => array( 'report_advanced_field2',
'report_advanced_field_label2' ),
'SUMINSURED' => array( 'report_advanced_field3',
'report_advanced_field_label3' ) ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ),
'top' => array( 'print_header',
'print_subheader' ),
'grid' => array( 'report_advanced_field_label1',
'report_advanced_field1',
'report_advanced_field_label2',
'report_advanced_field2',
'report_advanced_field_label3',
'report_advanced_field3' ) ),
'formXtTags' => array( 'above-grid' => array( 'print_pages' ),
'below-grid' => array(  ) ),
'itemForms' => array( 'print_pages' => 'above-grid',
'print_header' => 'top',
'print_subheader' => 'top',
'report_advanced_field_label1' => 'grid',
'report_advanced_field1' => 'grid',
'report_advanced_field_label2' => 'grid',
'report_advanced_field2' => 'grid',
'report_advanced_field_label3' => 'grid',
'report_advanced_field3' => 'grid' ),
'itemLocations' => array( 'report_advanced_field_label1' => array( 'location' => 'grid',
'cellId' => 'headcell_field1' ),
'report_advanced_field1' => array( 'location' => 'grid',
'cellId' => 'cell_field1' ),
'report_advanced_field_label2' => array( 'location' => 'grid',
'cellId' => 'headcell_field2' ),
'report_advanced_field2' => array( 'location' => 'grid',
'cellId' => 'cell_field2' ),
'report_advanced_field_label3' => array( 'location' => 'grid',
'cellId' => 'headcell_field3' ),
'report_advanced_field3' => array( 'location' => 'grid',
'cellId' => 'cell_field3' ) ),
'itemVisiblity' => array(  ) ),
'itemsByType' => array( 'print_header' => array( 'print_header' ),
'print_subheader' => array( 'print_subheader' ),
'print_pages' => array( 'print_pages' ),
'report_advanced_field' => array( 'report_advanced_field1',
'report_advanced_field2',
'report_advanced_field3' ),
'report_advanced_field_label' => array( 'report_advanced_field_label1',
'report_advanced_field_label2',
'report_advanced_field_label3' ) ),
'cellMaps' => array( 'grid' => array( 'cells' => array( 'headcell_field1' => array( 'cols' => array( 0 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'report_advanced_field_label1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'headcell_field2' => array( 'cols' => array( 1 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'report_advanced_field_label2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'headcell_field3' => array( 'cols' => array( 2 ),
'rows' => array( 0 ),
'tags' => array(  ),
'items' => array( 'report_advanced_field_label3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field1' => array( 'cols' => array( 0 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'report_advanced_field1' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field2' => array( 'cols' => array( 1 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'report_advanced_field2' ),
'fixedAtServer' => true,
'fixedAtClient' => false ),
'cell_field3' => array( 'cols' => array( 2 ),
'rows' => array( 1 ),
'tags' => array(  ),
'items' => array( 'report_advanced_field3' ),
'fixedAtServer' => true,
'fixedAtClient' => false ) ),
'width' => 3,
'height' => 2 ) ) ),
'loginForm' => array( 'loginForm' => 3 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array( 'print_pages' => array( 'tag' => 'PRINT_PAGES',
'type' => 2 ) ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => false ),
'misc' => array( 'type' => 'rprint',
'breadcrumb' => false ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'newreport' => array( 'reportInfo' => array( 'groupFields' => array(  ),
'fields' => array( array( 'field' => 'DATE',
'grid' => true ),
array( 'field' => 'KODECABANG',
'grid' => true ),
array( 'field' => 'SUMINSURED',
'grid' => true ) ),
'showData' => true,
'pageSummary' => false,
'globalSummary' => false,
'crosstab' => false ) ) );
			$pageArray = array( 'id' => 'rprint',
'type' => 'rprint',
'layoutId' => 'basic',
'disabled' => 0,
'default' => 0,
'forms' => array( 'above-grid' => array( 'modelId' => 'print-above-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'print_pages' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'below-grid' => array( 'modelId' => 'print-below-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array(  ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'print-header',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c2' => array( 'model' => 'c2',
'items' => array( 'print_header',
'print_subheader' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'grid' => array( 'modelId' => 'report-plain',
'grid' => array( array( 'section' => 'head',
'cells' => array( array( 'cell' => 'headcell_field1' ),
array( 'cell' => 'headcell_field2' ),
array( 'cell' => 'headcell_field3' ) ) ),
array( 'cells' => array( array( 'cell' => 'cell_field1' ),
array( 'cell' => 'cell_field2' ),
array( 'cell' => 'cell_field3' ) ),
'section' => 'body' ) ),
'cells' => array( 'headcell_field1' => array( 'model' => 'headcell_field',
'items' => array( 'report_advanced_field_label1' ),
'field' => 'DATE' ),
'cell_field1' => array( 'model' => 'cell_field',
'items' => array( 'report_advanced_field1' ),
'field' => 'DATE',
'columnName' => 'field' ),
'headcell_field2' => array( 'model' => 'headcell_field',
'items' => array( 'report_advanced_field_label2' ),
'field' => 'KODECABANG' ),
'cell_field2' => array( 'model' => 'cell_field',
'items' => array( 'report_advanced_field2' ),
'field' => 'KODECABANG',
'columnName' => 'field' ),
'headcell_field3' => array( 'model' => 'headcell_field',
'items' => array( 'report_advanced_field_label3' ),
'field' => 'SUMINSURED' ),
'cell_field3' => array( 'model' => 'cell_field',
'items' => array( 'report_advanced_field3' ),
'field' => 'SUMINSURED',
'columnName' => 'field' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1,
'groupColors' => array(  ) ) ),
'items' => array( 'print_header' => array( 'type' => 'print_header' ),
'print_subheader' => array( 'type' => 'print_subheader' ),
'print_pages' => array( 'type' => 'print_pages' ),
'report_advanced_field1' => array( 'field' => 'DATE',
'type' => 'report_advanced_field' ),
'report_advanced_field_label1' => array( 'type' => 'report_advanced_field_label',
'field' => 'DATE',
'label' => array( 'field' => 'DATE',
'table' => 'TEMPBSICIS_view',
'type' => 3 ) ),
'report_advanced_field2' => array( 'field' => 'KODECABANG',
'type' => 'report_advanced_field' ),
'report_advanced_field_label2' => array( 'type' => 'report_advanced_field_label',
'field' => 'KODECABANG',
'label' => array( 'field' => 'KODECABANG',
'table' => 'TEMPBSICIS_view',
'type' => 3 ) ),
'report_advanced_field3' => array( 'field' => 'SUMINSURED',
'type' => 'report_advanced_field' ),
'report_advanced_field_label3' => array( 'type' => 'report_advanced_field_label',
'field' => 'SUMINSURED',
'label' => array( 'field' => 'SUMINSURED',
'table' => 'TEMPBSICIS_view',
'type' => 3 ) ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>