<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'grid' => array( 'snippet',
'dashboard-item',
'dashboard-item3',
'dashboard-item1',
'dashboard-item4',
'dashboard-item2',
'dashboard-item6' ),
'supertop' => array( 'logo',
'menu',
'simple_search',
'notifications',
'loginform_login',
'username_button' ),
'top' => array( 'breadcrumb' ) ),
'formXtTags' => array( 'top' => array( 'breadcrumb' ) ),
'itemForms' => array( 'snippet' => 'grid',
'dashboard-item' => 'grid',
'dashboard-item3' => 'grid',
'dashboard-item1' => 'grid',
'dashboard-item4' => 'grid',
'dashboard-item2' => 'grid',
'dashboard-item6' => 'grid',
'logo' => 'supertop',
'menu' => 'supertop',
'simple_search' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'breadcrumb' => 'top' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'menu' => 3,
'simple_search' => 3,
'username_button' => 3,
'loginform_login' => 3 ) ),
'itemsByType' => array( 'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'snippet' => array( 'snippet' ),
'dashboard-item' => array( 'dashboard-item',
'dashboard-item1',
'dashboard-item2',
'dashboard-item3',
'dashboard-item4',
'dashboard-item6' ),
'changepassword_link' => array( 'changepassword_link' ),
'notifications' => array( 'notifications' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'dashboard',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dashboard' => array( 'elements' => array( array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v1_snippet3',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '#f5f5f5',
'bodyColor' => '',
'panelBorder' => '3px',
'borderColor' => '#f1f1f1',
'snippetStyle' => 'right',
'iconColor' => '' ),
'elementName' => 'LOGIN_snippet',
'table' => 'LOGIN',
'type' => 7,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'snippetId' => 'v1_snippet3',
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'TEMPBSICILE_view1',
'dashType' => 0,
'dashName' => 'TEMPBSICILE_view1_grid',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'elementName' => 'TEMPBSICILE_view1_grid',
'table' => 'TEMPBSICILE_view1',
'pageName' => 'list',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet1',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v1_snippet4',
'snippetStyle' => 'right',
'headerColor' => '',
'bodyBg' => '#f5f5f5',
'bodyColor' => '',
'iconColor' => '',
'panelBorder' => '3px',
'borderColor' => '#f1f1f1' ),
'elementName' => 'LOGIN_snippet1',
'table' => 'LOGIN',
'type' => 7,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'snippetId' => 'v1_snippet4',
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'TEMPBSICILE_view',
'dashType' => 1,
'dashName' => 'TEMPBSICILE_view_chart',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Total 5 Transaksi Per Cabang' ),
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'elementName' => 'TEMPBSICILE_view_chart',
'table' => 'TEMPBSICILE_view',
'type' => 1,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet2',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v1_snippet5',
'snippetStyle' => 'right',
'headerColor' => '',
'bodyBg' => '#f5f5f5',
'bodyColor' => '',
'iconColor' => '',
'panelBorder' => '3px',
'borderColor' => '#f1f1f1' ),
'elementName' => 'LOGIN_snippet2',
'table' => 'LOGIN',
'type' => 7,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'snippetId' => 'v1_snippet5',
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'primary' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'TOTAL_PREMI_SI',
'dashType' => 0,
'dashName' => 'TOTAL_PREMI_SI_grid',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'elementName' => 'TOTAL_PREMI_SI_grid',
'table' => 'TOTAL_PREMI_SI',
'pageName' => 'list',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ) ) ),
'dashSearch' => array( 'searchFields' => array( 'LOGIN_id_m_login' => array( array( 'field' => 'id_m_login',
'table' => 'LOGIN' ) ),
'LOGIN_username' => array( array( 'field' => 'username',
'table' => 'LOGIN' ) ),
'LOGIN_password' => array( array( 'field' => 'password',
'table' => 'LOGIN' ) ),
'LOGIN_fullname' => array( array( 'field' => 'fullname',
'table' => 'LOGIN' ) ),
'LOGIN_email' => array( array( 'field' => 'email',
'table' => 'LOGIN' ) ),
'LOGIN_api_keys' => array( array( 'field' => 'api_keys',
'table' => 'LOGIN' ) ),
'TEMPBSICILE_view_Total' => array( array( 'field' => 'Total',
'table' => 'TEMPBSICILE_view' ) ),
'TEMPBSICILE_view_NMCBGBANK' => array( array( 'field' => 'NMCBGBANK',
'table' => 'TEMPBSICILE_view' ) ),
'TOTAL_PREMI_SI_ID' => array( array( 'field' => 'ID',
'table' => 'TOTAL_PREMI_SI' ) ),
'TOTAL_PREMI_SI_TAHUN' => array( array( 'field' => 'TAHUN',
'table' => 'TOTAL_PREMI_SI' ) ),
'TOTAL_PREMI_SI_BULAN' => array( array( 'field' => 'BULAN',
'table' => 'TOTAL_PREMI_SI' ) ),
'TOTAL_PREMI_SI_PERTANGGUNGAN' => array( array( 'field' => 'PERTANGGUNGAN',
'table' => 'TOTAL_PREMI_SI' ) ),
'TOTAL_PREMI_SI_PREMI' => array( array( 'field' => 'PREMI',
'table' => 'TOTAL_PREMI_SI' ) ),
'TEMPBSICILE_view1_Kode_Cabang' => array( array( 'field' => 'Kode_Cabang',
'table' => 'TEMPBSICILE_view1' ) ),
'TEMPBSICILE_view1_Kantor_Cabang' => array( array( 'field' => 'Kantor_Cabang',
'table' => 'TEMPBSICILE_view1' ) ),
'TEMPBSICILE_view1_Total_pertanggungan' => array( array( 'field' => 'Total_pertanggungan',
'table' => 'TEMPBSICILE_view1' ) ),
'TEMPBSICILE_view1_TAHUN_PERIODE' => array( array( 'field' => 'TAHUN_PERIODE',
'table' => 'TEMPBSICILE_view1' ) ) ),
'allSearchFields' => array( 'LOGIN_id_m_login',
'LOGIN_username',
'LOGIN_password',
'LOGIN_fullname',
'LOGIN_email',
'LOGIN_api_keys',
'TEMPBSICILE_view_Total',
'TEMPBSICILE_view_NMCBGBANK',
'TOTAL_PREMI_SI_ID',
'TOTAL_PREMI_SI_TAHUN',
'TOTAL_PREMI_SI_BULAN',
'TOTAL_PREMI_SI_PERTANGGUNGAN',
'TOTAL_PREMI_SI_PREMI',
'TEMPBSICILE_view1_Kode_Cabang',
'TEMPBSICILE_view1_Kantor_Cabang',
'TEMPBSICILE_view1_Total_pertanggungan',
'TEMPBSICILE_view1_TAHUN_PERIODE' ),
'googleLikeFields' => array( 'LOGIN_id_m_login',
'LOGIN_username',
'LOGIN_password',
'LOGIN_fullname',
'LOGIN_email',
'LOGIN_api_keys' ) ) );
			$pageArray = array( 'id' => 'dashboard',
'type' => 'dashboard',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'grid' => array( 'modelId' => 'dashboard-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 3 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c' ),
array( 'cell' => 'c4' ),
array( 'cell' => 'c6',
'colspan' => 1 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'snippet' ),
'width' => '' ),
'c' => array( 'model' => 'c1',
'items' => array( 'dashboard-item',
'dashboard-item3' ),
'width' => '100%' ),
'c4' => array( 'model' => 'c1',
'items' => array( 'dashboard-item1',
'dashboard-item4' ),
'width' => '100%' ),
'c6' => array( 'model' => 'c1',
'items' => array( 'dashboard-item2',
'dashboard-item6' ),
'width' => '100%' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'topbar-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'notifications',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'dashboard-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'breadcrumb' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'snippet' => array( 'eventId' => 'v1_snippet2',
'label' => array( 'text' => 'v1_snippet2',
'type' => 0 ),
'type' => 'snippet' ),
'dashboard-item' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v1_snippet3',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '#f5f5f5',
'bodyColor' => '',
'panelBorder' => '3px',
'borderColor' => '#f1f1f1',
'snippetStyle' => 'right',
'iconColor' => '' ),
'dashboard-item1' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet1',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v1_snippet4',
'snippetStyle' => 'right',
'headerColor' => '',
'bodyBg' => '#f5f5f5',
'bodyColor' => '',
'iconColor' => '',
'panelBorder' => '3px',
'borderColor' => '#f1f1f1' ),
'dashboard-item2' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet2',
'bsStyle' => 'primary',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v1_snippet5',
'snippetStyle' => 'right',
'headerColor' => '',
'bodyBg' => '#f5f5f5',
'bodyColor' => '',
'iconColor' => '',
'panelBorder' => '3px',
'borderColor' => '#f1f1f1' ),
'dashboard-item3' => array( 'type' => 'dashboard-item',
'table' => 'TEMPBSICILE_view1',
'dashType' => 0,
'dashName' => 'TEMPBSICILE_view1_grid',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'dashboard-item4' => array( 'type' => 'dashboard-item',
'table' => 'TEMPBSICILE_view',
'dashType' => 1,
'dashName' => 'TEMPBSICILE_view_chart',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Total 5 Transaksi Per Cabang' ),
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'dashboard-item6' => array( 'type' => 'dashboard-item',
'table' => 'TOTAL_PREMI_SI',
'dashType' => 0,
'dashName' => 'TOTAL_PREMI_SI_grid',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '500px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'pageId' => 'list',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'notifications' => array( 'type' => 'notifications' ) ),
'dbProps' => array(  ),
'version' => 11,
'pageAlign' => 'center',
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>