<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'grid' => array( 'dashboard-item',
'dashboard-item1',
'snippet',
'dashboard-item3',
'dashboard-item2',
'dashboard-item5',
'dashboard-item4',
'dashboard-item6' ),
'supertop' => array( 'logo',
'menu',
'simple_search',
'notifications',
'loginform_login',
'username_button' ),
'top' => array( 'breadcrumb' ) ),
'formXtTags' => array( 'top' => array( 'breadcrumb' ) ),
'itemForms' => array( 'dashboard-item' => 'grid',
'dashboard-item1' => 'grid',
'snippet' => 'grid',
'dashboard-item3' => 'grid',
'dashboard-item2' => 'grid',
'dashboard-item5' => 'grid',
'dashboard-item4' => 'grid',
'dashboard-item6' => 'grid',
'logo' => 'supertop',
'menu' => 'supertop',
'simple_search' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'breadcrumb' => 'top' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'menu' => 3,
'simple_search' => 3,
'username_button' => 3,
'loginform_login' => 3 ) ),
'itemsByType' => array( 'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'snippet' => array( 'snippet' ),
'dashboard-item' => array( 'dashboard-item',
'dashboard-item1',
'dashboard-item2',
'dashboard-item3',
'dashboard-item4',
'dashboard-item5',
'dashboard-item6' ),
'changepassword_link' => array( 'changepassword_link' ),
'notifications' => array( 'notifications' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'dashboard',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dashboard' => array( 'elements' => array( array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v2_snippet1',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'panelBorder' => null,
'borderColor' => '' ),
'elementName' => 'LOGIN_snippet',
'table' => 'LOGIN',
'type' => 7,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'snippetId' => 'v2_snippet1',
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet1',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v2_snippet2',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'panelBorder' => null,
'borderColor' => '' ),
'elementName' => 'LOGIN_snippet1',
'table' => 'LOGIN',
'type' => 7,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'snippetId' => 'v2_snippet2',
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet2',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v2_snippet3',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'panelBorder' => null,
'borderColor' => '' ),
'elementName' => 'LOGIN_snippet2',
'table' => 'LOGIN',
'type' => 7,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'snippetId' => 'v2_snippet3',
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet3',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v2_snippet4',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'panelBorder' => null,
'borderColor' => '' ),
'elementName' => 'LOGIN_snippet3',
'table' => 'LOGIN',
'type' => 7,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'snippetId' => 'v2_snippet4',
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'TEMPBSICIS_view2',
'dashType' => 1,
'dashName' => 'TEMPBSICIS_view2_chart',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '400px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'customLabel' => true,
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'dashLabel' => array( 'type' => 0,
'text' => 'Top 5 Uang Pertanggungan by Chart' ) ),
'elementName' => 'TEMPBSICIS_view2_chart',
'table' => 'TEMPBSICIS_view2',
'type' => 1,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'TEMPBSICIS_view1',
'dashType' => 0,
'dashName' => 'TEMPBSICIS_view1_grid',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '400px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Top 10 Uang Pertanggungan' ),
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null ),
'elementName' => 'TEMPBSICIS_view1_grid',
'table' => 'TEMPBSICIS_view1',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'TEMPBSICIS_view3',
'dashType' => 0,
'dashName' => 'TEMPBSICIS_view3_grid',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'fa' => 'flag' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '800px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Proposal dan Nilai Premi' ),
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null ),
'elementName' => 'TEMPBSICIS_view3_grid',
'table' => 'TEMPBSICIS_view3',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ) ) ),
'dashSearch' => array( 'searchFields' => array( 'LOGIN_id_m_login' => array( array( 'field' => 'id_m_login',
'table' => 'LOGIN' ) ),
'LOGIN_username' => array( array( 'field' => 'username',
'table' => 'LOGIN' ) ),
'LOGIN_password' => array( array( 'field' => 'password',
'table' => 'LOGIN' ) ),
'LOGIN_fullname' => array( array( 'field' => 'fullname',
'table' => 'LOGIN' ) ),
'LOGIN_email' => array( array( 'field' => 'email',
'table' => 'LOGIN' ) ),
'LOGIN_api_keys' => array( array( 'field' => 'api_keys',
'table' => 'LOGIN' ) ),
'LOGIN_id_ext' => array( array( 'field' => 'id_ext',
'table' => 'LOGIN' ) ),
'LOGIN_two_factor' => array( array( 'field' => 'two_factor',
'table' => 'LOGIN' ) ),
'LOGIN_totp' => array( array( 'field' => 'totp',
'table' => 'LOGIN' ) ),
'TEMPBSICIS_view1_CIS_AREA' => array( array( 'field' => 'CIS_AREA',
'table' => 'TEMPBSICIS_view1' ) ),
'TEMPBSICIS_view1_Cabang' => array( array( 'field' => 'Cabang',
'table' => 'TEMPBSICIS_view1' ) ),
'TEMPBSICIS_view1_Periode' => array( array( 'field' => 'Periode',
'table' => 'TEMPBSICIS_view1' ) ),
'TEMPBSICIS_view1_SUMINSURED' => array( array( 'field' => 'SUMINSURED',
'table' => 'TEMPBSICIS_view1' ) ),
'TEMPBSICIS_view1_CIS_UPL_USER' => array( array( 'field' => 'CIS_UPL_USER',
'table' => 'TEMPBSICIS_view1' ) ),
'TEMPBSICIS_view1_CIS_UPL_DATE' => array( array( 'field' => 'CIS_UPL_DATE',
'table' => 'TEMPBSICIS_view1' ) ),
'TEMPBSICIS_view1_CIS_FL' => array( array( 'field' => 'CIS_FL',
'table' => 'TEMPBSICIS_view1' ) ),
'TEMPBSICIS_view1_IDCIS' => array( array( 'field' => 'IDCIS',
'table' => 'TEMPBSICIS_view1' ) ),
'TEMPBSICIS_view1_CIS_TOKEN' => array( array( 'field' => 'CIS_TOKEN',
'table' => 'TEMPBSICIS_view1' ) ),
'TEMPBSICIS_view1_CIS_REGION' => array( array( 'field' => 'CIS_REGION',
'table' => 'TEMPBSICIS_view1' ) ),
'TEMPBSICIS_view2_KODECABANG' => array( array( 'field' => 'KODECABANG',
'table' => 'TEMPBSICIS_view2' ) ),
'TEMPBSICIS_view2_SUMINSURED' => array( array( 'field' => 'SUMINSURED',
'table' => 'TEMPBSICIS_view2' ) ),
'TEMPBSICIS_view3_CIS_PROPOSAL' => array( array( 'field' => 'CIS_PROPOSAL',
'table' => 'TEMPBSICIS_view3' ) ),
'TEMPBSICIS_view3_CIS_PREMI' => array( array( 'field' => 'CIS_PREMI',
'table' => 'TEMPBSICIS_view3' ) ),
'TEMPBSICIS_view3_CIS_PERIODE_END' => array( array( 'field' => 'CIS_PERIODE_END',
'table' => 'TEMPBSICIS_view3' ) ),
'TEMPBSICIS_view3_KODECABANG' => array( array( 'field' => 'KODECABANG',
'table' => 'TEMPBSICIS_view3' ) ) ),
'allSearchFields' => array( 'LOGIN_id_m_login',
'LOGIN_username',
'LOGIN_password',
'LOGIN_fullname',
'LOGIN_email',
'LOGIN_api_keys',
'LOGIN_id_ext',
'LOGIN_two_factor',
'LOGIN_totp',
'TEMPBSICIS_view1_CIS_AREA',
'TEMPBSICIS_view1_Cabang',
'TEMPBSICIS_view1_Periode',
'TEMPBSICIS_view1_SUMINSURED',
'TEMPBSICIS_view1_CIS_UPL_USER',
'TEMPBSICIS_view1_CIS_UPL_DATE',
'TEMPBSICIS_view1_CIS_FL',
'TEMPBSICIS_view1_IDCIS',
'TEMPBSICIS_view1_CIS_TOKEN',
'TEMPBSICIS_view1_CIS_REGION',
'TEMPBSICIS_view2_KODECABANG',
'TEMPBSICIS_view2_SUMINSURED',
'TEMPBSICIS_view3_CIS_PROPOSAL',
'TEMPBSICIS_view3_CIS_PREMI',
'TEMPBSICIS_view3_CIS_PERIODE_END',
'TEMPBSICIS_view3_KODECABANG' ),
'googleLikeFields' => array( 'LOGIN_id_m_login',
'LOGIN_username',
'LOGIN_password',
'LOGIN_fullname',
'LOGIN_email',
'LOGIN_api_keys',
'LOGIN_id_ext',
'LOGIN_two_factor',
'LOGIN_totp' ) ) );
			$pageArray = array( 'id' => 'dashboard',
'type' => 'dashboard',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'grid' => array( 'modelId' => 'dashboard-grid',
'grid' => array( array( 'section' => '',
'cells' => array( array( 'cell' => 'c4',
'colspan' => 4 ) ) ),
array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c' ),
array( 'cell' => 'c10' ),
array( 'cell' => 'c7' ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c5',
'colspan' => 3 ),
array( 'cell' => 'c11' ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'dashboard-item' ),
'width' => '100%' ),
'c' => array( 'model' => 'c1',
'items' => array( 'dashboard-item1' ),
'width' => '100%' ),
'c4' => array( 'model' => 'c1',
'items' => array( 'snippet' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'dashboard-item3' ) ),
'c10' => array( 'model' => 'c1',
'items' => array( 'dashboard-item2' ),
'width' => '100%' ),
'c5' => array( 'model' => 'c1',
'items' => array( 'dashboard-item5',
'dashboard-item4' ),
'width' => '' ),
'c11' => array( 'model' => 'c1',
'items' => array( 'dashboard-item6' ),
'width' => '' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'topbar-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'notifications',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'dashboard-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'breadcrumb' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'snippet' => array( 'eventId' => 'v2_snippet',
'label' => array( 'text' => 'v2_snippet',
'type' => 0 ),
'type' => 'snippet' ),
'dashboard-item' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v2_snippet1',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'panelBorder' => null,
'borderColor' => '' ),
'dashboard-item1' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet1',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v2_snippet2',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'panelBorder' => null,
'borderColor' => '' ),
'dashboard-item2' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet2',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v2_snippet3',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'panelBorder' => null,
'borderColor' => '' ),
'dashboard-item3' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet3',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v2_snippet4',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'panelBorder' => null,
'borderColor' => '' ),
'dashboard-item4' => array( 'type' => 'dashboard-item',
'table' => 'TEMPBSICIS_view1',
'dashType' => 0,
'dashName' => 'TEMPBSICIS_view1_grid',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '400px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Top 10 Uang Pertanggungan' ),
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null ),
'dashboard-item5' => array( 'type' => 'dashboard-item',
'table' => 'TEMPBSICIS_view2',
'dashType' => 1,
'dashName' => 'TEMPBSICIS_view2_chart',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '400px',
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null,
'customLabel' => true,
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'dashLabel' => array( 'type' => 0,
'text' => 'Top 5 Uang Pertanggungan by Chart' ) ),
'dashboard-item6' => array( 'type' => 'dashboard-item',
'table' => 'TEMPBSICIS_view3',
'dashType' => 0,
'dashName' => 'TEMPBSICIS_view3_grid',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'fa' => 'flag' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '800px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'Proposal dan Nilai Premi' ),
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'notifications' => array( 'type' => 'notifications' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>