<?php
			$optionsArray = array( 'fields' => array( 'gridFields' => array(  ),
'searchRequiredFields' => array(  ),
'searchPanelFields' => array(  ),
'fieldItems' => array(  ) ),
'pageLinks' => array( 'edit' => false,
'add' => false,
'view' => false,
'print' => false ),
'layoutHelper' => array( 'formItems' => array( 'formItems' => array( 'grid' => array( 'snippet',
'dashboard-item',
'dashboard-item1',
'dashboard-item3',
'dashboard-item2',
'dashboard-item4',
'dashboard-item6',
'dashboard-item5' ),
'supertop' => array( 'logo',
'menu',
'simple_search',
'notifications',
'loginform_login',
'username_button' ),
'top' => array( 'breadcrumb' ) ),
'formXtTags' => array( 'top' => array( 'breadcrumb' ) ),
'itemForms' => array( 'snippet' => 'grid',
'dashboard-item' => 'grid',
'dashboard-item1' => 'grid',
'dashboard-item3' => 'grid',
'dashboard-item2' => 'grid',
'dashboard-item4' => 'grid',
'dashboard-item6' => 'grid',
'dashboard-item5' => 'grid',
'logo' => 'supertop',
'menu' => 'supertop',
'simple_search' => 'supertop',
'notifications' => 'supertop',
'loginform_login' => 'supertop',
'username_button' => 'supertop',
'breadcrumb' => 'top' ),
'itemLocations' => array(  ),
'itemVisiblity' => array( 'menu' => 3,
'simple_search' => 3,
'username_button' => 3,
'loginform_login' => 3 ) ),
'itemsByType' => array( 'breadcrumb' => array( 'breadcrumb' ),
'logo' => array( 'logo' ),
'menu' => array( 'menu' ),
'simple_search' => array( 'simple_search' ),
'username_button' => array( 'username_button' ),
'loginform_login' => array( 'loginform_login' ),
'userinfo_link' => array( 'userinfo_link' ),
'logout_link' => array( 'logout_link' ),
'adminarea_link' => array( 'adminarea_link' ),
'changepassword_link' => array( 'changepassword_link' ),
'snippet' => array( 'snippet' ),
'dashboard-item' => array( 'dashboard-item',
'dashboard-item1',
'dashboard-item2',
'dashboard-item3',
'dashboard-item4',
'dashboard-item5',
'dashboard-item6' ),
'notifications' => array( 'notifications' ) ),
'cellMaps' => array(  ) ),
'loginForm' => array( 'loginForm' => 0 ),
'page' => array( 'verticalBar' => false,
'labeledButtons' => array( 'update_records' => array(  ),
'print_pages' => array(  ),
'register_activate_message' => array(  ),
'details_found' => array(  ) ),
'hasCustomButtons' => false,
'customButtons' => array(  ),
'hasNotifications' => true ),
'misc' => array( 'type' => 'dashboard',
'breadcrumb' => true ),
'events' => array( 'maps' => array(  ),
'mapsData' => array(  ),
'buttons' => array(  ) ),
'dashboard' => array( 'elements' => array( array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'fa' => 'th-list' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v4_snippet',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'iconColor' => '',
'panelBorder' => '',
'borderColor' => '',
'headerBg' => '' ),
'elementName' => 'LOGIN_snippet',
'table' => 'LOGIN',
'type' => 7,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'snippetId' => 'v4_snippet',
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet1',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'fa' => 'th-list' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v4_snippet1',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'panelBorder' => null,
'borderColor' => '' ),
'elementName' => 'LOGIN_snippet1',
'table' => 'LOGIN',
'type' => 7,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'snippetId' => 'v4_snippet1',
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet2',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'fa' => 'th-list' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v4_snippet2',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'panelBorder' => null,
'borderColor' => '' ),
'elementName' => 'LOGIN_snippet2',
'table' => 'LOGIN',
'type' => 7,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'snippetId' => 'v4_snippet2',
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet3',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'fa' => 'th-list' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v4_snippet3',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'panelBorder' => null,
'borderColor' => '' ),
'elementName' => 'LOGIN_snippet3',
'table' => 'LOGIN',
'type' => 7,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'snippetId' => 'v4_snippet3',
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'sp_summary_product',
'dashType' => 0,
'dashName' => 'sp_summary_product_grid',
'bsStyle' => 'default',
'panelType' => 1,
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '200px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'TOTAL KOMISI BY PRODUK' ),
'icon' => array( 'fa' => 'tag' ),
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null ),
'elementName' => 'sp_summary_product_grid',
'table' => 'sp_summary_product',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'Chart_summary_report_view',
'dashType' => 1,
'dashName' => 'Chart_summary_report_view_chart',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '620px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'TOTAL KOMISI BY PRODUK ' ),
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null ),
'elementName' => 'Chart_summary_report_view_chart',
'table' => 'Chart_summary_report_view',
'type' => 1,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ),
array( 'item' => array( 'type' => 'dashboard-item',
'table' => 'report_product_Month',
'dashType' => 0,
'dashName' => 'report_product_Month_grid',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '400px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null ),
'elementName' => 'report_product_Month_grid',
'table' => 'report_product_Month',
'type' => 0,
'reload' => 0,
'tabsPageTypes' => array(  ),
'pageNames' => array(  ),
'initialTabPageType' => 'view',
'notUsedDetailTables' => array(  ),
'details' => array(  ),
'zoom' => 'undefined',
'updateMoved' => true,
'masterTable' => '',
'tabLocation' => 'above',
'panelStyle' => 'default' ) ) ),
'dashSearch' => array( 'searchFields' => array( 'LOGIN_id_m_login' => array( array( 'field' => 'id_m_login',
'table' => 'LOGIN' ) ),
'LOGIN_username' => array( array( 'field' => 'username',
'table' => 'LOGIN' ) ),
'LOGIN_password' => array( array( 'field' => 'password',
'table' => 'LOGIN' ) ),
'LOGIN_fullname' => array( array( 'field' => 'fullname',
'table' => 'LOGIN' ) ),
'LOGIN_email' => array( array( 'field' => 'email',
'table' => 'LOGIN' ) ),
'LOGIN_api_keys' => array( array( 'field' => 'api_keys',
'table' => 'LOGIN' ) ),
'LOGIN_id_ext' => array( array( 'field' => 'id_ext',
'table' => 'LOGIN' ) ),
'LOGIN_two_factor' => array( array( 'field' => 'two_factor',
'table' => 'LOGIN' ) ),
'LOGIN_totp' => array( array( 'field' => 'totp',
'table' => 'LOGIN' ) ),
'LOGIN_reset_token' => array( array( 'field' => 'reset_token',
'table' => 'LOGIN' ) ),
'LOGIN_reset_date' => array( array( 'field' => 'reset_date',
'table' => 'LOGIN' ) ),
'sp_summary_product_KETERANGAN' => array( array( 'field' => 'KETERANGAN',
'table' => 'sp_summary_product' ) ),
'sp_summary_product_Suminsured' => array( array( 'field' => 'Suminsured',
'table' => 'sp_summary_product' ) ),
'sp_summary_product_Premi' => array( array( 'field' => 'Premi',
'table' => 'sp_summary_product' ) ),
'sp_summary_product_Komisi' => array( array( 'field' => 'Komisi',
'table' => 'sp_summary_product' ) ),
'Chart_summary_report_view_KETERANGAN' => array( array( 'field' => 'KETERANGAN',
'table' => 'Chart_summary_report_view' ) ),
'Chart_summary_report_view_Suminsured' => array( array( 'field' => 'Suminsured',
'table' => 'Chart_summary_report_view' ) ),
'Chart_summary_report_view_Premi' => array( array( 'field' => 'Premi',
'table' => 'Chart_summary_report_view' ) ),
'Chart_summary_report_view_Komisi' => array( array( 'field' => 'Komisi',
'table' => 'Chart_summary_report_view' ) ),
'report_product_Month_YEARS' => array( array( 'field' => 'YEARS',
'table' => 'report_product_Month' ) ),
'report_product_Month_MONTHS' => array( array( 'field' => 'MONTHS',
'table' => 'report_product_Month' ) ),
'report_product_Month_SUM_B_SUMINSURED_' => array( array( 'field' => 'SUM(B.SUMINSURED)',
'table' => 'report_product_Month' ) ),
'report_product_Month_SUM_B_KOMISI_' => array( array( 'field' => 'SUM(B.KOMISI)',
'table' => 'report_product_Month' ) ),
'report_product_Month_KETERANGAN' => array( array( 'field' => 'KETERANGAN',
'table' => 'report_product_Month' ) ) ),
'allSearchFields' => array( 'LOGIN_id_m_login',
'LOGIN_username',
'LOGIN_password',
'LOGIN_fullname',
'LOGIN_email',
'LOGIN_api_keys',
'LOGIN_id_ext',
'LOGIN_two_factor',
'LOGIN_totp',
'LOGIN_reset_token',
'LOGIN_reset_date',
'sp_summary_product_KETERANGAN',
'sp_summary_product_Suminsured',
'sp_summary_product_Premi',
'sp_summary_product_Komisi',
'Chart_summary_report_view_KETERANGAN',
'Chart_summary_report_view_Suminsured',
'Chart_summary_report_view_Premi',
'Chart_summary_report_view_Komisi',
'report_product_Month_YEARS',
'report_product_Month_MONTHS',
'report_product_Month_SUM_B_SUMINSURED_',
'report_product_Month_SUM_B_KOMISI_',
'report_product_Month_KETERANGAN' ),
'googleLikeFields' => array( 'LOGIN_id_m_login',
'LOGIN_username',
'LOGIN_password',
'LOGIN_fullname',
'LOGIN_email',
'LOGIN_api_keys',
'LOGIN_id_ext',
'LOGIN_two_factor',
'LOGIN_totp',
'LOGIN_reset_token',
'LOGIN_reset_date' ) ) );
			$pageArray = array( 'id' => 'dashboard',
'type' => 'dashboard',
'layoutId' => 'topbar',
'disabled' => 0,
'default' => 0,
'forms' => array( 'grid' => array( 'modelId' => 'dashboard-grid',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1',
'colspan' => 4 ) ),
'section' => '' ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c2' ),
array( 'cell' => 'c3' ),
array( 'cell' => 'c7' ),
array( 'cell' => 'c5' ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c9',
'colspan' => 2 ),
array( 'cell' => 'c11',
'colspan' => 2,
'rowspan' => 2 ) ) ),
array( 'section' => '',
'cells' => array( array( 'cell' => 'c10',
'colspan' => 2 ) ) ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'snippet' ) ),
'c2' => array( 'model' => 'c1',
'items' => array( 'dashboard-item' ) ),
'c3' => array( 'model' => 'c1',
'items' => array( 'dashboard-item1' ) ),
'c5' => array( 'model' => 'c1',
'items' => array( 'dashboard-item3' ) ),
'c7' => array( 'model' => 'c1',
'items' => array( 'dashboard-item2' ) ),
'c9' => array( 'model' => 'c1',
'items' => array( 'dashboard-item4' ),
'width' => '',
'zeroHeight' => true ),
'c10' => array( 'model' => 'c1',
'items' => array( 'dashboard-item6' ),
'width' => '' ),
'c11' => array( 'model' => 'c1',
'items' => array( 'dashboard-item5' ),
'width' => '' ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'supertop' => array( 'modelId' => 'topbar-dashboard',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ),
array( 'cell' => 'c2' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'logo',
'menu' ) ),
'c2' => array( 'model' => 'c2',
'items' => array( 'simple_search',
'notifications',
'loginform_login',
'username_button' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ),
'top' => array( 'modelId' => 'dashboard-top',
'grid' => array( array( 'cells' => array( array( 'cell' => 'c1' ) ),
'section' => '' ) ),
'cells' => array( 'c1' => array( 'model' => 'c1',
'items' => array( 'breadcrumb' ) ) ),
'deferredItems' => array(  ),
'recsPerRow' => 1 ) ),
'items' => array( 'breadcrumb' => array( 'type' => 'breadcrumb' ),
'logo' => array( 'type' => 'logo' ),
'menu' => array( 'type' => 'menu' ),
'simple_search' => array( 'type' => 'simple_search' ),
'username_button' => array( 'type' => 'username_button',
'items' => array( 'userinfo_link',
'logout_link',
'adminarea_link',
'changepassword_link' ) ),
'loginform_login' => array( 'type' => 'loginform_login',
'popup' => false ),
'userinfo_link' => array( 'type' => 'userinfo_link' ),
'logout_link' => array( 'type' => 'logout_link' ),
'adminarea_link' => array( 'type' => 'adminarea_link' ),
'changepassword_link' => array( 'type' => 'changepassword_link' ),
'snippet' => array( 'type' => 'snippet',
'eventId' => 'v2_snippet',
'label' => array( 'text' => 'v2_snippet',
'type' => 0 ) ),
'dashboard-item' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'fa' => 'th-list' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v4_snippet',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'iconColor' => '',
'panelBorder' => '',
'borderColor' => '',
'headerBg' => '' ),
'dashboard-item1' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet1',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'fa' => 'th-list' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v4_snippet1',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'panelBorder' => null,
'borderColor' => '' ),
'dashboard-item2' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet2',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'fa' => 'th-list' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v4_snippet2',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'panelBorder' => null,
'borderColor' => '' ),
'dashboard-item3' => array( 'type' => 'dashboard-item',
'table' => 'LOGIN',
'dashType' => 7,
'dashName' => 'LOGIN_snippet3',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'fa' => 'th-list' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'eventId' => 'v4_snippet3',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'panelBorder' => null,
'borderColor' => '' ),
'dashboard-item4' => array( 'type' => 'dashboard-item',
'table' => 'sp_summary_product',
'dashType' => 0,
'dashName' => 'sp_summary_product_grid',
'bsStyle' => 'default',
'panelType' => 1,
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '200px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'TOTAL KOMISI BY PRODUK' ),
'icon' => array( 'fa' => 'tag' ),
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null ),
'dashboard-item5' => array( 'type' => 'dashboard-item',
'table' => 'Chart_summary_report_view',
'dashType' => 1,
'dashName' => 'Chart_summary_report_view_chart',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '620px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'customLabel' => true,
'dashLabel' => array( 'type' => 0,
'text' => 'TOTAL KOMISI BY PRODUK ' ),
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null ),
'dashboard-item6' => array( 'type' => 'dashboard-item',
'table' => 'report_product_Month',
'dashType' => 0,
'dashName' => 'report_product_Month_grid',
'bsStyle' => 'default',
'panelType' => 1,
'icon' => array( 'glyph' => '' ),
'viewTab' => true,
'editTab' => true,
'addTab' => true,
'initialTab' => 0,
'hiddenDetails' => array(  ),
'detailsOptions' => array(  ),
'mapUpdateGridWhenMoved' => true,
'height' => '400px',
'headerBg' => '',
'headerColor' => '',
'bodyBg' => '',
'bodyColor' => '',
'footerBg' => '',
'panelBorder' => null,
'borderColor' => '',
'innerBorder' => null,
'innerBorderColor' => null,
'reloadInterval' => 0,
'detailsFilterByMaster' => false,
'detailsMasterTable' => null ),
'notifications' => array( 'type' => 'notifications' ) ),
'dbProps' => array(  ),
'version' => 11,
'imageItem' => array( 'type' => 'page_image' ),
'imageBgColor' => '#f2f2f2',
'controlsBgColor' => 'white',
'imagePosition' => 'right' );
		?>