<?php
$securitySettings_var = array( 'providers' => array( array( 'type' => '%db',
'activationField' => '˂Create new˃',
'active' => true,
'code' => '00',
'emailField' => 'email',
'extUserIdField' => null,
'fullnameField' => 'fullname',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'resetDateField' => 'reset_date',
'resetTokenField' => 'reset_token',
'table' => array( 'connId' => 'u736239518_btn_at_154_41_241_2',
'table' => 'LOGIN' ),
'userGroupField' => 'username',
'usernameField' => 'username',
'userpicField' => 'userpic' ) ),
'sessionControl' => array( 'lifeTime' => 15,
'sessionName' => 'PxIRvYwKUqaeBUTRoJAw',
'JWTSecret' => 'wu3MRZiu5DLmBNFOIebF',
'forceExpire' => true,
'keepAlive' => false ),
'registration' => array( 'passwordValidation' => array( 'strong' => true,
'minimumLength' => 8,
'uniqueCharacters' => 4,
'digitsAndSymbols' => 2,
'upperAndLowerCase' => true ),
'remindMethod' => 1,
'hashAlgorithm' => 0,
'changePasswordPage' => true,
'changePwdPage' => true,
'hashPassword' => false,
'registerPage' => false,
'remindPage' => true,
'remindPasswordPage' => true ),
'captchaSettings' => array( 'captchaType' => 1,
'siteKey' => '6LcXZQYqAAAAAIohV2d2GKPglLbrSll1sPbBg6Y8',
'secretKey' => '6LcXZQYqAAAAAK6n8pDn3_yArhGgzOBsiLAsyNQh',
'passesCount' => 5 ),
'emailSettings' => array( 'fromEmail' => 'no-reply@talisman.co.id',
'usePHPDefinedSMTP' => false,
'useBuiltInMailer' => false,
'SMTPServer' => 'smtp-mail.outlook.com',
'SMTPPort' => 587,
'SMTPUser' => 'no-reply@talisman.co.id',
'SMTPPassword' => 'No2019reply!',
'securityProtocol' => 2 ),
'advancedSecurity' => array( 'allowGuestLogin' => false ),
'auditAndLocking' => array( 'loggingTable' => array( 'connId' => 'u736239518_btn_at_154_41_241_2',
'table' => 'btn_new__audit' ),
'lockingTable' => array( 'connId' => 'u736239518_btn_at_154_41_241_2',
'table' => '˂Create new˃' ),
'tables' => array( 'LOGIN' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'SURAT' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'TEMBSICITASAL' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'TEMBSICITTUJUAN' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'TEMPBSICILE' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'TEMPBSICILE_view1' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'TEMPBSICIS' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'TEMPBSICIS_view1' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'TEMPBSICIS_view3' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'TEMPBSICIT' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'TOTAL_PREMI_SI' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'Upload_cabang' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'admin_members' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'admin_rights' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'admin_users' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'hasil_proses_api' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'hasil_proses_api1' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'report_upload_file' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ),
'upload_year_month' => array( 'logFieldValues' => true,
'logModifications' => true,
'recordLocking' => false ) ),
'loggingMode' => 1,
'loggingFile' => 'audit.log',
'logSecurityActions' => true,
'lockAfterUnsuccessfulLogin' => false,
'enableLocking' => false ),
'twoFactorSettings' => array( 'available' => false,
'required' => true,
'enable' => true,
'remember' => true,
'types' => array( 'totp' => true ),
'twoFactorField' => 'two_factor',
'emailField' => 'email',
'phoneField' => '˂Create new˃',
'codeField' => 'totp',
'projectName' => 'BSI' ),
'projectName' => 'BSIupload',
'loginDataSource' => 'LOGIN',
'loginForm' => 0,
'dynamicPermissions' => true,
'dpTablePrefix' => 'LOG_',
'dpTableConnId' => 'u736239518_btn_at_154_41_241_2',
'hardcodedLogin' => false,
'enabled' => true,
'advancedSecurityAvailable' => true,
'userGroupsAvailable' => true,
'defaultProviderCode' => '00',
'adOnlyLogin' => false,
'dbProvider' => array( 'type' => '%db',
'activationField' => '˂Create new˃',
'active' => true,
'code' => '00',
'emailField' => 'email',
'extUserIdField' => null,
'fullnameField' => 'fullname',
'label' => array( 'text' => 'Database',
'type' => 0 ),
'name' => 'db',
'passwordField' => 'password',
'resetDateField' => 'reset_date',
'resetTokenField' => 'reset_token',
'table' => array( 'connId' => 'u736239518_btn_at_154_41_241_2',
'table' => 'LOGIN' ),
'userGroupField' => 'username',
'usernameField' => 'username',
'userpicField' => 'userpic' ),
'adAdminGroups' => array(  ),
'showUserSource' => false,
'dbProviderCodes' => array( '00' ),
'notifications' => array( 'enabled' => true,
'table' => array( 'connId' => 'u736239518_btn_at_154_41_241_2',
'table' => 'bsiupload_noti' ) ) );
?>