<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_tempbsicis_ol  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowView"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowView(&$xt, &$templatefile, &$values, $pageObject)
{

		if($values['CIS_FL'] == 2){
	$pageObject->showItem("custom_button");
}else{
	$pageObject->hideItem("custom_button");
}
// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeShowView

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>