<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_tempbsicit_verifikasi  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeShowEdit"]=true;

		$this->events["BeforeShowView"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowEdit(&$xt, &$templatefile, $values, $pageObject)
{

		$ol = $values['IS_OL'];

if($ol == 1){
	$pageObject->hideItem("integrated_edit_field12");
}else{
	$pageObject->hideItem("integrated_edit_field12");
}

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeShowEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before display
function BeforeShowView(&$xt, &$templatefile, &$values, $pageObject)
{

		$ol = $values['IS_OL'];

if($ol == 1){
	$pageObject->hideItem("integrated_edit_field12");
}else{
	$pageObject->hideItem("integrated_edit_field12");
}

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function BeforeShowView

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>