<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_tempbsicis_kc  extends eventsBase
{
	function __construct()
	{
	// fill list of events
		$this->events["BeforeInsert"]=true;

		$this->events["BeforeEdit"]=true;

		$this->events["AfterEdit"]=true;


	}

//	handlers

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before Insert Record
function BeforeInsert(&$rawvalues, &$values, $pageObject, &$message)
{

		$userData = Security::getUserName();

// Get Local Date Time
	$tz = 'Asia/Jakarta';
	$dt = new DateTime("now", new DateTimeZone($tz));
	$timestamp = $dt->format('Y-m-d h:i:s');
	$tahun = $dt->format("y");
	$bulan = $dt->format("m");
	$tanggal = $dt->format("d");

$values['CIS_UPL_USER'] = $userData;
$values['CIS_UPL_DATE'] = $timestamp;

$values['CIS_TIPE'] = "KC";
$suminsured = $values['SUMINSURED'];
$suminsured1 = number_format($values['SUMINSURED'],2,",",".");
$kodeResiko = "CIS-01";
$limit = 0;
$periodeAwal = new DateTime("now", new DateTimeZone($tz));
$periodeAwal1 = $periodeAwal->format('Y-m-d h:i:s');

//**********  Check if specific record exists  ************

$rs = DB::Query("select * from M_RESIKO where resiko_kode='".$kodeResiko."'");
$data=$rs->fetchAssoc();
if($data)
{
	$limit = $data["resiko_limit"];
}
else
{
	// if dont exist do something else
}

if($suminsured > $limit){
	$values['CIS_FL'] = 2; // kode 2 untuk overlimit
	
	$rs1 = DB::Query("select * from BSIBRANCH where IDBRANCH='".$values['KODECABANG']."'");
	$data1=$rs1->fetchAssoc();
	if($data1)
	{
		$cabangBSI = $data1["BRANCHNAME"];
	}

	// notifikasi overlimit
	$message="Pengajuan Overlimit Id KC BSI ".$values['KODECABANG'];
	$title = "[BSI-Cash In Safe] Notifikasi Overlimit";
	$icon = "fa-envelope"; 
	$url = "tempbsicis_ol_view.php?editid1=".$values['IDCIS'];
	$expire = 1440; 
	$permissions = "rega.tri";
	$newWindow = false;
	addNotification( $message,$title,$icon,$url,$expire,$permissions,$newWindow);

	// email overlimit
	$email="ricky.dwi@talisman.co.id";
	$from="no-reply@talisman.co.id";
	$msg="BSI x Talisman Aplication
	
	Overlimit Cash In Safe 
	Kantor Cabang BSI : $cabangBSI
	Tanggal Periode (Awal) : $periodeAwal1
	Nilai Pertanggungan : IDR $suminsured1
	Tipe Cash In Safe : CIS-KC
	
	Mohon untuk dapat ditindaklanjuti.

	no-reply@talisman.co.id
	BSI x Talisman Aplication
	";
	$subject="[BSI-Cash In Safe] Notifikasi Overlimit";

	$ret=runner_mail(array('to' => $email, 'subject' => $subject, 'body' => $msg, 'from'=>$from));
	if(!$ret["mailed"])
		echo $ret["message"];
}else{
	$values['CIS_FL'] = 0;
}
// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;
} // function BeforeInsert

		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Before record updated
function BeforeEdit(&$values, $where, &$oldvalues, &$keys, &$message, $inline, $pageObject)
{

		$values['CIS_TIPE'] = "KC";
$suminsured = $values['SUMINSURED'];
$kodeResiko = "CIS-01";
$limit = 0;

//**********  Check if specific record exists  ************

$rs = DB::Query("select * from M_RESIKO where resiko_kode='".$kodeResiko."'");
$data=$rs->fetchAssoc();
if($data)
{
	$limit = $data["resiko_limit"];
}
else
{
	// if dont exist do something else
}

if($suminsured > $limit){
	$values['CIS_FL'] = 2; // kode 2 untuk overlimit
}else{
	$values['CIS_FL'] = 0;
}

// Place event code here.
// Use "Add Action" button to add code snippets.

return true;
;
} // function BeforeEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values, $where, &$oldvalues, &$keys, $inline, $pageObject)
{

		if($values['CIS_FL'] == 2){	
	// notifikasi overlimit
	$message="Pengajuan Overlimit Id KC BSI ".$values['KODECABANG'];
	$title = "[BSI-Cash In Safe] Notifikasi Overlimit";
	$icon = "fa-envelope"; 
	$url = "tempbsicis_ol_view.php?editid1=".$values['IDCIS'];
	$expire = 1440; 
	$permissions = "rega.tri";
	$newWindow = false;
	addNotification( $message,$title,$icon,$url,$expire,$permissions,$newWindow);

	$rs1 = DB::Query("select * from BSIBRANCH where IDBRANCH='".$values['KODECABANG']."'");
	$data1=$rs1->fetchAssoc();
	if($data1)
	{
		$cabangBSI = $data1["BRANCHNAME"];
	}
	
	$tz = 'Asia/Jakarta';
	$suminsured = $values['SUMINSURED'];
	$suminsured1 = number_format($values['SUMINSURED'],2,",",".");
	$periodeAwal = new DateTime("now", new DateTimeZone($tz));
	$periodeAwal1 = $periodeAwal->format('Y-m-d h:i:s');	

	// email overlimit
	$email="ricky.dwi@talisman.co.id";
	$from="no-reply@talisman.co.id";
	$msg="BSI x Talisman Aplication
	
	Overlimit Cash In Safe 
	Kantor Cabang BSI : $cabangBSI
	Tanggal Periode (Awal) : $periodeAwal1
	Nilai Pertanggungan : IDR $suminsured1
	Tipe Cash In Safe : CIS-KC
	
	Mohon untuk dapat ditindaklanjuti.

	no-reply@talisman.co.id
	BSI x Talisman Aplication
	";
	$subject="[BSI-Cash In Safe] Notifikasi Overlimit";

	$ret=runner_mail(array('to' => $email, 'subject' => $subject, 'body' => $msg, 'from'=>$from));
	if(!$ret["mailed"])
		echo $ret["message"];
}

// Place event code here.
// Use "Add Action" button to add code snippets.
;
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		



}
?>