<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_v1  extends eventsBase
{
	function __construct()
	{
	// fill list of events

	}

//	handlers


		// dashboatd snippets function
	function event_v1_snippet( &$header, &$icon )
	{
		$header = "<p style='font-size:30px'>Upload</p>";
echo "<p style='font-size:20px'>2000 Record</p>";;
	}
		// dashboatd snippets function
	function event_v1_snippet1( &$header, &$icon )
	{
		$header = "Total Premi";
echo "1.000.000";;
	}
		// dashboatd snippets function
	function event_v1_snippet3( &$header, &$icon )
	{
		$header = "Total Data Upload";
$userData = Security::getUserName();

$rs2 = DB::Query("select count(NOLOANDISBURSE) as last_stock from TEMPBSICILE where adduser='".$userData."'");
$data2 = $rs2->fetchAssoc();
echo '<span style="font-size: 30px;"> ' .number_format($data2["last_stock"]).  '</span>';;
	}
		// dashboatd snippets function
	function event_v1_snippet4( &$header, &$icon )
	{
		$header = "Total Pokok Pembiayaan";
$userData = Security::getUserName();

$rs2 = DB::Query("select SUM(POKOKPEMBIAYAAN) as last_stock from TEMPBSICILE where adduser='".$userData."'");
$data2 = $rs2->fetchAssoc();
echo '<span style="font-size: 30px;"> ' .number_format($data2["last_stock"]).  '</span>';;
	}
		// dashboatd snippets function
	function event_v1_snippet5( &$header, &$icon )
	{
		$header = "Total User Online";
echo '<span style="font-size: 30px;">0</span>';;
	}

}
?>