<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_v2  extends eventsBase
{
	function __construct()
	{
	// fill list of events

	}

//	handlers


		// dashboatd snippets function
	function event_v2_snippet1( &$header, &$icon )
	{
		$header = "Total Data Upload";
$userData = Security::getUserName();
$cabang = $_SESSION["IdExt"];

$rs2 = DB::Query("select count(CIS_UPL_USER) as last_stock from TEMPBSICIS where KODECABANG='".$cabang."'");
$data2 = $rs2->fetchAssoc();
echo '<span style="font-size: 30px;"> ' .number_format($data2["last_stock"]).  '</span>';;
	}
		// dashboatd snippets function
	function event_v2_snippet2( &$header, &$icon )
	{
		$header = "Total Nilai Uang Pertanggungan";
$userData = Security::getUserName();
$cabang = $_SESSION["IdExt"];

$rs2 = DB::Query("select SUM(SUMINSURED) as last_stock from TEMPBSICIS where KODECABANG='".$cabang."'");
$data2 = $rs2->fetchAssoc();
echo '<span style="font-size: 30px;"> ' .number_format($data2["last_stock"]).  '</span>';;
	}
		// dashboatd snippets function
	function event_v2_snippet3( &$header, &$icon )
	{
		$header = "Total Cabang";
$userData = Security::getUserName();
$cabang = $_SESSION["IdExt"];

$rs2 = DB::Query("select count(KODECABANG) as cabang from TEMPBSICIS WHERE KODECABANG='".$cabang."' order by KODECABANG");
$data2 = $rs2->fetchAssoc();
echo '<span style="font-size: 30px;"> ' .number_format($data2["cabang"]).  '</span>';;
	}
		// dashboatd snippets function
	function event_v2_snippet4( &$header, &$icon )
	{
		$header = "Total Premi Asuransi";
$userData = Security::getUserName();
$cabang = $_SESSION["IdExt"];

$rs2 = DB::Query("select SUM(CIS_PREMI) as total from TEMPBSICIS WHERE KODECABANG='".$cabang."'");
$data2 = $rs2->fetchAssoc();
echo '<span style="font-size: 30px;"> ' .number_format($data2["total"]).  '</span>';;
	}

}
?>