<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_v3  extends eventsBase
{
	function __construct()
	{
	// fill list of events

	}

//	handlers


		// dashboatd snippets function
	function event_v3_snippet( &$header, &$icon )
	{
		$header = "Your header here";
echo "Your text here";;
	}
		// dashboatd snippets function
	function event_v3_snippet1( &$header, &$icon )
	{
		$header = "Total Data Register";
$userData = Security::getUserName();
$cabang = $_SESSION["IdExt"];

$rs2 = DB::Query("select count(IDCIT) as last_stock from TEMPBSICIT where CIT_IDCBG='".$cabang."'");
$data2 = $rs2->fetchAssoc();
echo '<span style="font-size: 30px;"> ' .number_format($data2["last_stock"]).  '</span>';;
	}
		// dashboatd snippets function
	function event_v3_snippet2( &$header, &$icon )
	{
		$header = "Total Nilai Uang Pertanggungan";
$userData = Security::getUserName();
$cabang = $_SESSION["IdExt"];

$rs2 = DB::Query("select SUM(CIT_TSI) as last_stock from TEMPBSICIT where CIT_IDCBG='".$cabang."'");
$data2 = $rs2->fetchAssoc();
echo '<span style="font-size: 30px;"> ' .number_format($data2["last_stock"]).  '</span>';;
	}
		// dashboatd snippets function
	function event_v3_snippet3( &$header, &$icon )
	{
		$header = "Total Cabang";
$userData = Security::getUserName();
$cabang = $_SESSION["IdExt"];

$rs2 = DB::Query("select count(CIT_IDCBG) as cabang from TEMPBSICIT WHERE CIT_IDCBG='".$cabang."' group by CIT_IDCBG");
$data2 = $rs2->fetchAssoc();
echo '<span style="font-size: 30px;"> ' .number_format($data2["cabang"]).  '</span>';;
	}
		// dashboatd snippets function
	function event_v3_snippet4( &$header, &$icon )
	{
		$header = "Total Premi Asuransi";
$userData = Security::getUserName();
$cabang = $_SESSION["IdExt"];

$rs2 = DB::Query("select SUM(CIT_PREMI) as total from TEMPBSICIT WHERE CIT_IDCBG='".$cabang."'");
$data2 = $rs2->fetchAssoc();
echo '<span style="font-size: 30px;"> ' .number_format($data2["total"]).  '</span>';;
	}

}
?>