<?php

/**
 * 	Dear developer!
 *	Never modify events.php file, it is autogenerated.
 *  Modify PHP/EventTemplates/events.txt instead.
 *
 */

 class eventclass_v4  extends eventsBase
{
	function __construct()
	{
	// fill list of events

	}

//	handlers


		// dashboatd snippets function
	function event_v4_snippet( &$header, &$icon )
	{
		$header = "TOTAL DATA TRANSAKSI";
$userData = Security::getUserName();

$rs2 = DB::Query("select count(NOLOANDISBURSE) as last_stock from TEMPBSICILE");
$data2 = $rs2->fetchAssoc();
$rs3 = DB::Query("select count(IDCIS) as last_stock from TEMPBSICIS");
$data3 = $rs3->fetchAssoc();
$rs4 = DB::Query("select count(IDCIT) as last_stock from TEMPBSICIT");
$data4 = $rs4->fetchAssoc();
$sum = $data2["last_stock"] + $data3["last_stock"] + $data4["last_stock"];
echo '<span style="font-size: 30px;"> ' .number_format($sum).  '</span>';;
	}
		// dashboatd snippets function
	function event_v4_snippet1( &$header, &$icon )
	{
		$header = "TOTAL NILAI PERTANGGUNGAN";
$userData = Security::getUserName();

$rs2 = DB::Query("select SUM(PERTANGGUNGAN) as last_stock from TOTAL_PREMI_SI");
$data2 = $rs2->fetchAssoc();
$rs3 = DB::Query("select SUM(SUMINSURED) as last_stock from TEMPBSICIS");
$data3 = $rs3->fetchAssoc();
$rs4 = DB::Query("select SUM(CIT_TSI) as last_stock from TEMPBSICIT");
$data4 = $rs4->fetchAssoc();
$sum = $data2["last_stock"] + $data3["last_stock"] + $data4["last_stock"];
echo '<span style="font-size: 30px;"> ' .number_format($sum).  '</span>';;
	}
		// dashboatd snippets function
	function event_v4_snippet2( &$header, &$icon )
	{
		$header = "TOTAL NILAI PREMI";
$userData = Security::getUserName();

$rs2 = DB::Query("select SUM(PREMI) as last_stock from TOTAL_PREMI_SI");
$data2 = $rs2->fetchAssoc();
$rs3 = DB::Query("select SUM(CIS_PREMI) as last_stock from TEMPBSICIS");
$data3 = $rs3->fetchAssoc();
$rs4 = DB::Query("select SUM(CIT_PREMI) as last_stock from TEMPBSICIT");
$data4 = $rs4->fetchAssoc();
$sum = $data2["last_stock"] + $data3["last_stock"] + $data4["last_stock"];
echo '<span style="font-size: 30px;"> ' .number_format($sum).  '</span>';
;
	}
		// dashboatd snippets function
	function event_v4_snippet3( &$header, &$icon )
	{
		$header = "TOTAL KOMISI";
$userData = Security::getUserName();

$rs2 = DB::Query("select SUM(PREMI)*20/100 as last_stock from TOTAL_PREMI_SI");
$data2 = $rs2->fetchAssoc();
$rs3 = DB::Query("select SUM(CIS_PREMI)*16.25/100 as last_stock from TEMPBSICIS");
$data3 = $rs3->fetchAssoc();
$rs4 = DB::Query("select SUM(CIT_PREMI)* 16.25/100 as last_stock from TEMPBSICIT");
$data4 = $rs4->fetchAssoc();
$sum = $data2["last_stock"] + $data3["last_stock"] + $data4["last_stock"];
echo '<span style="font-size: 30px;"> ' .number_format($sum).  '</span>';
;
	}

}
?>